using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using SecondDimension.Gameplay.GuildCity017D;

namespace SecondDimension.Gameplay.Campaign022
{
    internal static class CampaignStringList022
    {
        public static IReadOnlyList<string> CopyUniqueSorted(IReadOnlyList<string> values)
        {
            var result = new List<string>();
            var seen = new HashSet<string>(StringComparer.Ordinal);
            if (values != null)
                for (var i = 0; i < values.Count; i++)
                    if (!string.IsNullOrWhiteSpace(values[i]) && seen.Add(values[i]))
                        result.Add(values[i]);
            result.Sort(StringComparer.Ordinal);
            return result.AsReadOnly();
        }
    }

    public enum AbyssOperationStatus022 { Active, AwaitingBattle, ReadyToFinalize, Completed }
    public enum CovenantStatus022 { Locked, TrialAvailable, TrialActive, Accepted, Refused }

    [Serializable] public sealed class EquipmentEvolutionState022
    {
        [JsonConstructor] public EquipmentEvolutionState022(string itemInstanceId,string trackId,string tierId,int meaningfulUses,int masteryPoints,IReadOnlyList<string> appliedRecipeIds,string historyTag)
        { ItemInstanceId=Req(itemInstanceId,nameof(itemInstanceId));TrackId=Req(trackId,nameof(trackId));TierId=string.IsNullOrWhiteSpace(tierId)?"TRAINING":tierId;if(meaningfulUses<0||masteryPoints<0)throw new ArgumentOutOfRangeException(nameof(meaningfulUses));MeaningfulUses=meaningfulUses;MasteryPoints=masteryPoints;AppliedRecipeIds=Copy(appliedRecipeIds);HistoryTag=historyTag??string.Empty; }
        public string ItemInstanceId{get;} public string TrackId{get;} public string TierId{get;} public int MeaningfulUses{get;} public int MasteryPoints{get;} public IReadOnlyList<string> AppliedRecipeIds{get;} public string HistoryTag{get;}
        public EquipmentEvolutionState022 With(string tierId=null,int? meaningfulUses=null,int? masteryPoints=null,IReadOnlyList<string> appliedRecipeIds=null,string historyTag=null)=>new EquipmentEvolutionState022(ItemInstanceId,TrackId,tierId??TierId,meaningfulUses??MeaningfulUses,masteryPoints??MasteryPoints,appliedRecipeIds??AppliedRecipeIds,historyTag??HistoryTag);
        static string Req(string v,string p)=>string.IsNullOrWhiteSpace(v)?throw new ArgumentException("Stable ID required.",p):v; static IReadOnlyList<string> Copy(IReadOnlyList<string> v)=>CampaignStringList022.CopyUniqueSorted(v);
    }

    [Serializable] public sealed class ClassCertificationState022
    {
        [JsonConstructor] public ClassCertificationState022(string recruitId,string activeAdvancedClassId,IReadOnlyList<string> certifiedClassIds,IReadOnlyList<string> appliedCertificationReceiptIds)
        {RecruitId=Req(recruitId,nameof(recruitId));ActiveAdvancedClassId=activeAdvancedClassId??string.Empty;CertifiedClassIds=Copy(certifiedClassIds);AppliedCertificationReceiptIds=Copy(appliedCertificationReceiptIds);}
        public string RecruitId{get;} public string ActiveAdvancedClassId{get;} public IReadOnlyList<string> CertifiedClassIds{get;} public IReadOnlyList<string> AppliedCertificationReceiptIds{get;}
        public ClassCertificationState022 With(string activeAdvancedClassId=null,IReadOnlyList<string> certifiedClassIds=null,IReadOnlyList<string> appliedCertificationReceiptIds=null)=>new ClassCertificationState022(RecruitId,activeAdvancedClassId??ActiveAdvancedClassId,certifiedClassIds??CertifiedClassIds,appliedCertificationReceiptIds??AppliedCertificationReceiptIds);
        static string Req(string v,string p)=>string.IsNullOrWhiteSpace(v)?throw new ArgumentException("Stable ID required.",p):v; static IReadOnlyList<string> Copy(IReadOnlyList<string> v)=>CampaignStringList022.CopyUniqueSorted(v);
    }

    [Serializable] public sealed class AbyssStepReceiptProof022
    {
        [JsonConstructor] public AbyssStepReceiptProof022(string stepId,bool requiresBattle,string outcome,ProgressionReceipt022 receipt,string battleFinalStateHash,string existingBattleRewardReceiptId,string battleReturnReceiptId,string battleRequestId,string battleId,string returnCheckpointId,string battleReturnAuthorityId=null)
        {StepId=Req(stepId,nameof(stepId));RequiresBattle=requiresBattle;Outcome=Req(outcome,nameof(outcome));Receipt=receipt??throw new ArgumentNullException(nameof(receipt));BattleFinalStateHash=battleFinalStateHash??string.Empty;ExistingBattleRewardReceiptId=existingBattleRewardReceiptId??string.Empty;BattleReturnReceiptId=battleReturnReceiptId??string.Empty;BattleRequestId=battleRequestId??string.Empty;BattleId=battleId??string.Empty;ReturnCheckpointId=returnCheckpointId??string.Empty;BattleReturnAuthorityId=battleReturnAuthorityId??string.Empty;}
        public string StepId{get;} public bool RequiresBattle{get;} public string Outcome{get;} public ProgressionReceipt022 Receipt{get;} public string BattleFinalStateHash{get;} public string ExistingBattleRewardReceiptId{get;} public string BattleReturnReceiptId{get;} public string BattleRequestId{get;} public string BattleId{get;} public string ReturnCheckpointId{get;} public string BattleReturnAuthorityId{get;}
        static string Req(string v,string p)=>string.IsNullOrWhiteSpace(v)?throw new ArgumentException("Stable ID required.",p):v;
    }

    [Serializable] public sealed class AbyssFirstClearProof022
    {
        [JsonConstructor] public AbyssFirstClearProof022(string campaignGuid,long campaignSeed,int appliedReceiptCountAtBegin,string operationInstanceId,string operationDefinitionId,string floorId,string canonicalSeedIdentity,IReadOnlyList<string> completedStepIds,IReadOnlyList<AbyssStepReceiptProof022> stepReceipts,string existingBattleRewardReceiptId,ProgressionReceipt022 completionReceipt,int? committedOperationOrdinal=null,string previousAuthorityHash=null,string beginAuthorityHash=null,string alliedRosterIdentity=null,IReadOnlyList<string> alliedRecruitIds=null,int? floorClearCountAtBegin=null)
        {CampaignGuid=Req(campaignGuid,nameof(campaignGuid));CampaignSeed=campaignSeed;if(appliedReceiptCountAtBegin<0)throw new ArgumentOutOfRangeException(nameof(appliedReceiptCountAtBegin));AppliedReceiptCountAtBegin=appliedReceiptCountAtBegin;OperationInstanceId=Req(operationInstanceId,nameof(operationInstanceId));OperationDefinitionId=Req(operationDefinitionId,nameof(operationDefinitionId));FloorId=Req(floorId,nameof(floorId));CanonicalSeedIdentity=Req(canonicalSeedIdentity,nameof(canonicalSeedIdentity));CompletedStepIds=CopyStrings(completedStepIds);StepReceipts=CopySteps(stepReceipts);ExistingBattleRewardReceiptId=existingBattleRewardReceiptId??string.Empty;CompletionReceipt=completionReceipt??throw new ArgumentNullException(nameof(completionReceipt));CommittedOperationOrdinal=committedOperationOrdinal??-1;PreviousAuthorityHash=previousAuthorityHash??string.Empty;BeginAuthorityHash=beginAuthorityHash??string.Empty;AlliedRosterIdentity=alliedRosterIdentity??string.Empty;AlliedRecruitIds=CopyStrings(alliedRecruitIds);FloorClearCountAtBegin=floorClearCountAtBegin??-1;}
        public string CampaignGuid{get;} public long CampaignSeed{get;} public int AppliedReceiptCountAtBegin{get;} public string OperationInstanceId{get;} public string OperationDefinitionId{get;} public string FloorId{get;} public string CanonicalSeedIdentity{get;} public IReadOnlyList<string> CompletedStepIds{get;} public IReadOnlyList<AbyssStepReceiptProof022> StepReceipts{get;} public string ExistingBattleRewardReceiptId{get;} public ProgressionReceipt022 CompletionReceipt{get;} public int CommittedOperationOrdinal{get;} public string PreviousAuthorityHash{get;} public string BeginAuthorityHash{get;} public string AlliedRosterIdentity{get;} public IReadOnlyList<string> AlliedRecruitIds{get;} public int FloorClearCountAtBegin{get;}
        static string Req(string v,string p)=>string.IsNullOrWhiteSpace(v)?throw new ArgumentException("Stable ID required.",p):v;
        static IReadOnlyList<string> CopyStrings(IReadOnlyList<string> v){var r=new List<string>();if(v!=null)for(var i=0;i<v.Count;i++)r.Add(Req(v[i],nameof(v)));return r.AsReadOnly();}
        static IReadOnlyList<AbyssStepReceiptProof022> CopySteps(IReadOnlyList<AbyssStepReceiptProof022> v){var r=new List<AbyssStepReceiptProof022>();if(v!=null)for(var i=0;i<v.Count;i++)r.Add(v[i]??throw new ArgumentException("Step proof cannot be null.",nameof(v)));return r.AsReadOnly();}
    }

    [Serializable] public sealed class AbyssAuthorityEntry022
    {
        [JsonConstructor] public AbyssAuthorityEntry022(string previousHash,string entryHash,int sequenceIndex,int committedOperationOrdinal,string operationInstanceId,string operationDefinitionId,string floorId,AbyssFirstClearProof022 completionProof,bool? aborted=null,AbyssOperationState022 abortedOperation=null,TowerRestartDefeatProof130 towerRestart130=null)
        {PreviousHash=Req(previousHash,nameof(previousHash));EntryHash=Req(entryHash,nameof(entryHash));if(sequenceIndex<=0||committedOperationOrdinal<=0)throw new ArgumentOutOfRangeException(nameof(sequenceIndex));SequenceIndex=sequenceIndex;CommittedOperationOrdinal=committedOperationOrdinal;OperationInstanceId=Req(operationInstanceId,nameof(operationInstanceId));OperationDefinitionId=Req(operationDefinitionId,nameof(operationDefinitionId));FloorId=Req(floorId,nameof(floorId));Aborted=aborted??false;CompletionProof=completionProof;AbortedOperation=abortedOperation;TowerRestart130=towerRestart130;if(TowerRestart130!=null&&!Aborted)throw new ArgumentException("A Tower restart requires an aborted operation.",nameof(towerRestart130));if(Aborted==(CompletionProof!=null)||Aborted!=(AbortedOperation!=null))throw new ArgumentException("Authority entry must contain exactly one completion or aborted operation proof.",nameof(completionProof));}
        public string PreviousHash{get;} public string EntryHash{get;} public int SequenceIndex{get;} public int CommittedOperationOrdinal{get;} public string OperationInstanceId{get;} public string OperationDefinitionId{get;} public string FloorId{get;} public AbyssFirstClearProof022 CompletionProof{get;} public bool Aborted{get;} public AbyssOperationState022 AbortedOperation{get;}
        [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
        public TowerRestartDefeatProof130 TowerRestart130{get;}
        static string Req(string v,string p)=>string.IsNullOrWhiteSpace(v)?throw new ArgumentException("Stable ID required.",p):v;
    }

    [Serializable] public sealed class AbyssBeginGrant022
    {
        [JsonConstructor] public AbyssBeginGrant022(string beginAuthorityHash,string previousAuthorityHash,int committedOperationOrdinal,string operationInstanceId,string operationDefinitionId,string floorId,int appliedReceiptCountAtBegin,int floorClearCountAtBegin,string alliedRosterIdentity,IReadOnlyList<string> alliedRecruitIds)
        {BeginAuthorityHash=Req(beginAuthorityHash,nameof(beginAuthorityHash));PreviousAuthorityHash=Req(previousAuthorityHash,nameof(previousAuthorityHash));if(committedOperationOrdinal<=0||appliedReceiptCountAtBegin<0||floorClearCountAtBegin<0)throw new ArgumentOutOfRangeException(nameof(committedOperationOrdinal));CommittedOperationOrdinal=committedOperationOrdinal;OperationInstanceId=Req(operationInstanceId,nameof(operationInstanceId));OperationDefinitionId=Req(operationDefinitionId,nameof(operationDefinitionId));FloorId=Req(floorId,nameof(floorId));AppliedReceiptCountAtBegin=appliedReceiptCountAtBegin;FloorClearCountAtBegin=floorClearCountAtBegin;AlliedRosterIdentity=Req(alliedRosterIdentity,nameof(alliedRosterIdentity));AlliedRecruitIds=Copy(alliedRecruitIds);}
        public string BeginAuthorityHash{get;} public string PreviousAuthorityHash{get;} public int CommittedOperationOrdinal{get;} public string OperationInstanceId{get;} public string OperationDefinitionId{get;} public string FloorId{get;} public int AppliedReceiptCountAtBegin{get;} public int FloorClearCountAtBegin{get;} public string AlliedRosterIdentity{get;} public IReadOnlyList<string> AlliedRecruitIds{get;}
        static string Req(string v,string p)=>string.IsNullOrWhiteSpace(v)?throw new ArgumentException("Stable ID required.",p):v; static IReadOnlyList<string> Copy(IReadOnlyList<string> v)=>CampaignStringList022.CopyUniqueSorted(v);
    }

    [Serializable] public sealed class LegacyAbyssOperationArchive022
    {
        [JsonConstructor] public LegacyAbyssOperationArchive022(string archiveId,
            AbyssOperationState022 operation,EncounterLaunchRequest017D pendingEncounter,
            BattleReturnReceipt017D pendingBattleReturn,int operationOrdinal,
            string checkpointId)
        {ArchiveId=string.IsNullOrWhiteSpace(archiveId)?throw new ArgumentException(
            "Archive ID required.",nameof(archiveId)):archiveId;Operation=operation??
            throw new ArgumentNullException(nameof(operation));PendingEncounter=pendingEncounter;
            PendingBattleReturn=pendingBattleReturn;OperationOrdinal=Math.Max(0,
            operationOrdinal);CheckpointId=checkpointId??string.Empty;}
        public string ArchiveId{get;} public AbyssOperationState022 Operation{get;}
        public EncounterLaunchRequest017D PendingEncounter{get;}
        public BattleReturnReceipt017D PendingBattleReturn{get;}
        public int OperationOrdinal{get;} public string CheckpointId{get;}
    }

    [Serializable] public sealed class AbyssFloorProgressState022
    {
        [JsonConstructor] public AbyssFloorProgressState022(string floorId,int clearCount,int highestJudgmentTier,bool firstClearApplied,bool marginResolved,IReadOnlyList<string> appliedReceiptIds,AbyssFirstClearProof022 firstClearProof=null)
        {FloorId=Req(floorId,nameof(floorId));if(clearCount<0||highestJudgmentTier<0)throw new ArgumentOutOfRangeException(nameof(clearCount));ClearCount=clearCount;HighestJudgmentTier=highestJudgmentTier;FirstClearApplied=firstClearApplied;MarginResolved=marginResolved;AppliedReceiptIds=Copy(appliedReceiptIds);FirstClearProof=firstClearProof;}
        public string FloorId{get;} public int ClearCount{get;} public int HighestJudgmentTier{get;} public bool FirstClearApplied{get;} public bool MarginResolved{get;} public IReadOnlyList<string> AppliedReceiptIds{get;} public AbyssFirstClearProof022 FirstClearProof{get;}
        public AbyssFloorProgressState022 With(int? clearCount=null,int? highestJudgmentTier=null,bool? firstClearApplied=null,bool? marginResolved=null,IReadOnlyList<string> appliedReceiptIds=null,AbyssFirstClearProof022 firstClearProof=null)=>new AbyssFloorProgressState022(FloorId,clearCount??ClearCount,highestJudgmentTier??HighestJudgmentTier,firstClearApplied??FirstClearApplied,marginResolved??MarginResolved,appliedReceiptIds??AppliedReceiptIds,firstClearProof??FirstClearProof);
        static string Req(string v,string p)=>string.IsNullOrWhiteSpace(v)?throw new ArgumentException("Stable ID required.",p):v; static IReadOnlyList<string> Copy(IReadOnlyList<string> v)=>CampaignStringList022.CopyUniqueSorted(v);
    }

    [Serializable] public sealed class ProgressionReceipt022
    {
        [JsonConstructor] public ProgressionReceipt022(string receiptId,string sourceId,string outcome,string authoritativeHash,int guildXp,int hallXp,int summonResonance,IReadOnlyList<string> materialIds,int appliedVersion)
        {ReceiptId=Req(receiptId,nameof(receiptId));SourceId=Req(sourceId,nameof(sourceId));Outcome=Req(outcome,nameof(outcome));AuthoritativeHash=Req(authoritativeHash,nameof(authoritativeHash));if(guildXp<0||hallXp<0||summonResonance<0||appliedVersion<0)throw new ArgumentOutOfRangeException(nameof(guildXp));GuildXp=guildXp;HallXp=hallXp;SummonResonance=summonResonance;MaterialIds=Copy(materialIds);AppliedVersion=appliedVersion;}
        public string ReceiptId{get;} public string SourceId{get;} public string Outcome{get;} public string AuthoritativeHash{get;} public int GuildXp{get;} public int HallXp{get;} public int SummonResonance{get;} public IReadOnlyList<string> MaterialIds{get;} public int AppliedVersion{get;}
        static string Req(string v,string p)=>string.IsNullOrWhiteSpace(v)?throw new ArgumentException("Stable ID required.",p):v; static IReadOnlyList<string> Copy(IReadOnlyList<string> v)=>CampaignStringList022.CopyUniqueSorted(v);
    }

    [Serializable] public sealed class AbyssOperationState022
    {
        [JsonConstructor] public AbyssOperationState022(string operationInstanceId,string operationDefinitionId,string floorId,int currentStepIndex,AbyssOperationStatus022 status,IReadOnlyList<string> completedStepIds,ProgressionReceipt022 pendingReceipt,string existingBattleRewardReceiptId,string canonicalSeedIdentity,int? appliedReceiptCountAtBegin=null,IReadOnlyList<AbyssStepReceiptProof022> appliedStepProofs=null,int? committedOperationOrdinal=null,string previousAuthorityHash=null,string beginAuthorityHash=null,string alliedRosterIdentity=null,IReadOnlyList<string> alliedRecruitIds=null,int? floorClearCountAtBegin=null)
        {OperationInstanceId=Req(operationInstanceId,nameof(operationInstanceId));OperationDefinitionId=Req(operationDefinitionId,nameof(operationDefinitionId));FloorId=Req(floorId,nameof(floorId));if(currentStepIndex<0||(appliedReceiptCountAtBegin.HasValue&&appliedReceiptCountAtBegin.Value<0))throw new ArgumentOutOfRangeException(nameof(currentStepIndex));CurrentStepIndex=currentStepIndex;Status=status;CompletedStepIds=Copy(completedStepIds);PendingReceipt=pendingReceipt;ExistingBattleRewardReceiptId=existingBattleRewardReceiptId??string.Empty;CanonicalSeedIdentity=Req(canonicalSeedIdentity,nameof(canonicalSeedIdentity));AppliedReceiptCountAtBegin=appliedReceiptCountAtBegin;AppliedStepProofs=CopyProofs(appliedStepProofs);CommittedOperationOrdinal=committedOperationOrdinal??-1;PreviousAuthorityHash=previousAuthorityHash??string.Empty;BeginAuthorityHash=beginAuthorityHash??string.Empty;AlliedRosterIdentity=alliedRosterIdentity??string.Empty;AlliedRecruitIds=Copy(alliedRecruitIds);FloorClearCountAtBegin=floorClearCountAtBegin??-1;}
        public string OperationInstanceId{get;} public string OperationDefinitionId{get;} public string FloorId{get;} public int CurrentStepIndex{get;} public AbyssOperationStatus022 Status{get;} public IReadOnlyList<string> CompletedStepIds{get;} public ProgressionReceipt022 PendingReceipt{get;} public string ExistingBattleRewardReceiptId{get;} public string CanonicalSeedIdentity{get;} public int? AppliedReceiptCountAtBegin{get;} public IReadOnlyList<AbyssStepReceiptProof022> AppliedStepProofs{get;} public int CommittedOperationOrdinal{get;} public string PreviousAuthorityHash{get;} public string BeginAuthorityHash{get;} public string AlliedRosterIdentity{get;} public IReadOnlyList<string> AlliedRecruitIds{get;} public int FloorClearCountAtBegin{get;}
        public AbyssOperationState022 With(int? currentStepIndex=null,AbyssOperationStatus022? status=null,IReadOnlyList<string> completedStepIds=null,ProgressionReceipt022 pendingReceipt=null,bool replacePendingReceipt=false,string existingBattleRewardReceiptId=null,IReadOnlyList<AbyssStepReceiptProof022> appliedStepProofs=null)=>new AbyssOperationState022(OperationInstanceId,OperationDefinitionId,FloorId,currentStepIndex??CurrentStepIndex,status??Status,completedStepIds??CompletedStepIds,replacePendingReceipt?pendingReceipt:PendingReceipt,existingBattleRewardReceiptId??ExistingBattleRewardReceiptId,CanonicalSeedIdentity,AppliedReceiptCountAtBegin,appliedStepProofs??AppliedStepProofs,CommittedOperationOrdinal,PreviousAuthorityHash,BeginAuthorityHash,AlliedRosterIdentity,AlliedRecruitIds,FloorClearCountAtBegin);
        static string Req(string v,string p)=>string.IsNullOrWhiteSpace(v)?throw new ArgumentException("Stable ID required.",p):v; static IReadOnlyList<string> Copy(IReadOnlyList<string> v){var r=new List<string>();if(v!=null)for(var i=0;i<v.Count;i++)if(!string.IsNullOrWhiteSpace(v[i]))r.Add(v[i]);return r.AsReadOnly();} static IReadOnlyList<AbyssStepReceiptProof022> CopyProofs(IReadOnlyList<AbyssStepReceiptProof022> v){var r=new List<AbyssStepReceiptProof022>();if(v!=null)for(var i=0;i<v.Count;i++)r.Add(v[i]??throw new ArgumentException("Step proof cannot be null.",nameof(v)));return r.AsReadOnly();}
    }

    [Serializable] public sealed class InvocationArtifactState022
    {
        [JsonConstructor] public InvocationArtifactState022(string instanceId,string baseId,IReadOnlyList<string> affixIds,string evolutionPathId,int evolutionStage,int resonance,bool playerLocked)
        {InstanceId=Req(instanceId,nameof(instanceId));BaseId=Req(baseId,nameof(baseId));AffixIds=Copy(affixIds);EvolutionPathId=evolutionPathId??string.Empty;if(evolutionStage<0||resonance<0)throw new ArgumentOutOfRangeException(nameof(evolutionStage));EvolutionStage=evolutionStage;Resonance=resonance;PlayerLocked=playerLocked;}
        public string InstanceId{get;} public string BaseId{get;} public IReadOnlyList<string> AffixIds{get;} public string EvolutionPathId{get;} public int EvolutionStage{get;} public int Resonance{get;} public bool PlayerLocked{get;}
        public InvocationArtifactState022 With(string evolutionPathId=null,int? evolutionStage=null,int? resonance=null,bool? playerLocked=null)=>new InvocationArtifactState022(InstanceId,BaseId,AffixIds,evolutionPathId??EvolutionPathId,evolutionStage??EvolutionStage,resonance??Resonance,playerLocked??PlayerLocked);
        static string Req(string v,string p)=>string.IsNullOrWhiteSpace(v)?throw new ArgumentException("Stable ID required.",p):v; static IReadOnlyList<string> Copy(IReadOnlyList<string> v)=>CampaignStringList022.CopyUniqueSorted(v);
    }

    [Serializable] public sealed class CovenantProgressState022
    {
        [JsonConstructor] public CovenantProgressState022(string covenantId,CovenantStatus022 status,int trialProgress,int trust,IReadOnlyList<string> appliedReceiptIds)
        {CovenantId=Req(covenantId,nameof(covenantId));if(trialProgress<0||trust<0||trust>100)throw new ArgumentOutOfRangeException(nameof(trialProgress));Status=status;TrialProgress=trialProgress;Trust=trust;AppliedReceiptIds=Copy(appliedReceiptIds);}
        public string CovenantId{get;} public CovenantStatus022 Status{get;} public int TrialProgress{get;} public int Trust{get;} public IReadOnlyList<string> AppliedReceiptIds{get;}
        public CovenantProgressState022 With(CovenantStatus022? status=null,int? trialProgress=null,int? trust=null,IReadOnlyList<string> appliedReceiptIds=null)=>new CovenantProgressState022(CovenantId,status??Status,trialProgress??TrialProgress,trust??Trust,appliedReceiptIds??AppliedReceiptIds);
        static string Req(string v,string p)=>string.IsNullOrWhiteSpace(v)?throw new ArgumentException("Stable ID required.",p):v; static IReadOnlyList<string> Copy(IReadOnlyList<string> v)=>CampaignStringList022.CopyUniqueSorted(v);
    }

    [Serializable] public sealed class CampaignProgressionState022
    {
        public const string ContentVersion="CAMPAIGN_PROGRESSION_ABYSS_COVENANT_022_2.0";
        [JsonConstructor] public CampaignProgressionState022(string contentVersion,IReadOnlyList<EquipmentEvolutionState022> equipmentEvolution,IReadOnlyList<ClassCertificationState022> classCertifications,IReadOnlyList<AbyssFloorProgressState022> abyssFloors,AbyssOperationState022 activeAbyssOperation,IReadOnlyList<InvocationArtifactState022> invocationArtifacts,IReadOnlyList<CovenantProgressState022> covenants,IReadOnlyList<string> aboveGroundChangeIds,IReadOnlyList<string> appliedReceiptIds,int summonResonance,string lastCheckpointId,string abyssAuthorityBaseHash=null,int? abyssAuthorityBaseOperationOrdinal=null,IReadOnlyList<AbyssFloorProgressState022> abyssAuthorityBaseFloors=null,IReadOnlyList<string> abyssAuthorityBaseReceiptIds=null,IReadOnlyList<string> abyssAuthorityBaseAboveGroundChangeIds=null,IReadOnlyList<AbyssAuthorityEntry022> abyssAuthorityEntries=null,string abyssAuthorityHash=null,string abyssAuthorityMigrationReceiptId=null,AbyssBeginGrant022 activeAbyssBeginGrant=null,IReadOnlyList<AbyssStepReceiptProof022> activeAbyssStepLedger=null,IReadOnlyList<LegacyAbyssOperationArchive022> legacyAbyssOperationArchives=null)
        {ContentAuthorityVersion=string.IsNullOrWhiteSpace(contentVersion)?ContentVersion:contentVersion;EquipmentEvolution=CopyEq(equipmentEvolution);ClassCertifications=CopyClass(classCertifications);AbyssFloors=CopyFloors(abyssFloors);ActiveAbyssOperation=activeAbyssOperation;InvocationArtifacts=CopyArtifacts(invocationArtifacts);Covenants=CopyCovenants(covenants);AboveGroundChangeIds=CopyStrings(aboveGroundChangeIds);AppliedReceiptIds=CopyStrings(appliedReceiptIds);if(summonResonance<0)throw new ArgumentOutOfRangeException(nameof(summonResonance));SummonResonance=summonResonance;LastCheckpointId=lastCheckpointId??string.Empty;AbyssAuthorityBaseHash=abyssAuthorityBaseHash??string.Empty;AbyssAuthorityBaseOperationOrdinal=Math.Max(0,abyssAuthorityBaseOperationOrdinal??0);AbyssAuthorityBaseFloors=CopyFloors(abyssAuthorityBaseFloors);AbyssAuthorityBaseReceiptIds=CopyStrings(abyssAuthorityBaseReceiptIds);AbyssAuthorityBaseAboveGroundChangeIds=CopyStrings(abyssAuthorityBaseAboveGroundChangeIds);AbyssAuthorityEntries=CopyAuthorityEntries(abyssAuthorityEntries);AbyssAuthorityHash=abyssAuthorityHash??string.Empty;AbyssAuthorityMigrationReceiptId=abyssAuthorityMigrationReceiptId??string.Empty;ActiveAbyssBeginGrant=activeAbyssBeginGrant;ActiveAbyssStepLedger=CopyStepProofs(activeAbyssStepLedger);LegacyAbyssOperationArchives=CopyArchives(legacyAbyssOperationArchives);}
        public string ContentAuthorityVersion{get;} public IReadOnlyList<EquipmentEvolutionState022> EquipmentEvolution{get;} public IReadOnlyList<ClassCertificationState022> ClassCertifications{get;} public IReadOnlyList<AbyssFloorProgressState022> AbyssFloors{get;} public AbyssOperationState022 ActiveAbyssOperation{get;} public IReadOnlyList<InvocationArtifactState022> InvocationArtifacts{get;} public IReadOnlyList<CovenantProgressState022> Covenants{get;} public IReadOnlyList<string> AboveGroundChangeIds{get;} public IReadOnlyList<string> AppliedReceiptIds{get;} public int SummonResonance{get;} public string LastCheckpointId{get;} public string AbyssAuthorityBaseHash{get;} public int AbyssAuthorityBaseOperationOrdinal{get;} public IReadOnlyList<AbyssFloorProgressState022> AbyssAuthorityBaseFloors{get;} public IReadOnlyList<string> AbyssAuthorityBaseReceiptIds{get;} public IReadOnlyList<string> AbyssAuthorityBaseAboveGroundChangeIds{get;} public IReadOnlyList<AbyssAuthorityEntry022> AbyssAuthorityEntries{get;} public string AbyssAuthorityHash{get;} public string AbyssAuthorityMigrationReceiptId{get;} public AbyssBeginGrant022 ActiveAbyssBeginGrant{get;} public IReadOnlyList<AbyssStepReceiptProof022> ActiveAbyssStepLedger{get;} public IReadOnlyList<LegacyAbyssOperationArchive022> LegacyAbyssOperationArchives{get;}
        public CampaignProgressionState022 With(IReadOnlyList<EquipmentEvolutionState022> equipmentEvolution=null,IReadOnlyList<ClassCertificationState022> classCertifications=null,IReadOnlyList<AbyssFloorProgressState022> abyssFloors=null,AbyssOperationState022 activeAbyssOperation=null,bool replaceActiveAbyssOperation=false,IReadOnlyList<InvocationArtifactState022> invocationArtifacts=null,IReadOnlyList<CovenantProgressState022> covenants=null,IReadOnlyList<string> aboveGroundChangeIds=null,IReadOnlyList<string> appliedReceiptIds=null,int? summonResonance=null,string lastCheckpointId=null,string abyssAuthorityBaseHash=null,int? abyssAuthorityBaseOperationOrdinal=null,IReadOnlyList<AbyssFloorProgressState022> abyssAuthorityBaseFloors=null,IReadOnlyList<string> abyssAuthorityBaseReceiptIds=null,IReadOnlyList<string> abyssAuthorityBaseAboveGroundChangeIds=null,IReadOnlyList<AbyssAuthorityEntry022> abyssAuthorityEntries=null,string abyssAuthorityHash=null,string abyssAuthorityMigrationReceiptId=null,AbyssBeginGrant022 activeAbyssBeginGrant=null,bool replaceActiveAbyssBeginGrant=false,IReadOnlyList<AbyssStepReceiptProof022> activeAbyssStepLedger=null,IReadOnlyList<LegacyAbyssOperationArchive022> legacyAbyssOperationArchives=null)=>new CampaignProgressionState022(ContentAuthorityVersion,equipmentEvolution??EquipmentEvolution,classCertifications??ClassCertifications,abyssFloors??AbyssFloors,replaceActiveAbyssOperation?activeAbyssOperation:ActiveAbyssOperation,invocationArtifacts??InvocationArtifacts,covenants??Covenants,aboveGroundChangeIds??AboveGroundChangeIds,appliedReceiptIds??AppliedReceiptIds,summonResonance??SummonResonance,lastCheckpointId??LastCheckpointId,abyssAuthorityBaseHash??AbyssAuthorityBaseHash,abyssAuthorityBaseOperationOrdinal??AbyssAuthorityBaseOperationOrdinal,abyssAuthorityBaseFloors??AbyssAuthorityBaseFloors,abyssAuthorityBaseReceiptIds??AbyssAuthorityBaseReceiptIds,abyssAuthorityBaseAboveGroundChangeIds??AbyssAuthorityBaseAboveGroundChangeIds,abyssAuthorityEntries??AbyssAuthorityEntries,abyssAuthorityHash??AbyssAuthorityHash,abyssAuthorityMigrationReceiptId??AbyssAuthorityMigrationReceiptId,replaceActiveAbyssBeginGrant?activeAbyssBeginGrant:ActiveAbyssBeginGrant,activeAbyssStepLedger??ActiveAbyssStepLedger,legacyAbyssOperationArchives??LegacyAbyssOperationArchives);
        public static CampaignProgressionState022 Default()=>new CampaignProgressionState022(ContentVersion,Array.Empty<EquipmentEvolutionState022>(),Array.Empty<ClassCertificationState022>(),Array.Empty<AbyssFloorProgressState022>(),null,Array.Empty<InvocationArtifactState022>(),Array.Empty<CovenantProgressState022>(),Array.Empty<string>(),Array.Empty<string>(),0,"campaign022_initialized");
        static IReadOnlyList<string> CopyStrings(IReadOnlyList<string> v)=>CampaignStringList022.CopyUniqueSorted(v);
        static IReadOnlyList<EquipmentEvolutionState022> CopyEq(IReadOnlyList<EquipmentEvolutionState022> v){var r=new List<EquipmentEvolutionState022>();if(v!=null)for(var i=0;i<v.Count;i++)r.Add(v[i]??throw new ArgumentException("Equipment state cannot be null."));r.Sort((a,b)=>StringComparer.Ordinal.Compare(a.ItemInstanceId,b.ItemInstanceId));return r.AsReadOnly();}
        static IReadOnlyList<ClassCertificationState022> CopyClass(IReadOnlyList<ClassCertificationState022> v){var r=new List<ClassCertificationState022>();if(v!=null)for(var i=0;i<v.Count;i++)r.Add(v[i]??throw new ArgumentException("Class state cannot be null."));r.Sort((a,b)=>StringComparer.Ordinal.Compare(a.RecruitId,b.RecruitId));return r.AsReadOnly();}
        static IReadOnlyList<AbyssFloorProgressState022> CopyFloors(IReadOnlyList<AbyssFloorProgressState022> v){var r=new List<AbyssFloorProgressState022>();if(v!=null)for(var i=0;i<v.Count;i++)r.Add(v[i]??throw new ArgumentException("Floor state cannot be null."));r.Sort((a,b)=>StringComparer.Ordinal.Compare(a.FloorId,b.FloorId));return r.AsReadOnly();}
        static IReadOnlyList<InvocationArtifactState022> CopyArtifacts(IReadOnlyList<InvocationArtifactState022> v){var r=new List<InvocationArtifactState022>();if(v!=null)for(var i=0;i<v.Count;i++)r.Add(v[i]??throw new ArgumentException("Artifact state cannot be null."));r.Sort((a,b)=>StringComparer.Ordinal.Compare(a.InstanceId,b.InstanceId));return r.AsReadOnly();}
        static IReadOnlyList<CovenantProgressState022> CopyCovenants(IReadOnlyList<CovenantProgressState022> v){var r=new List<CovenantProgressState022>();if(v!=null)for(var i=0;i<v.Count;i++)r.Add(v[i]??throw new ArgumentException("Covenant state cannot be null."));r.Sort((a,b)=>StringComparer.Ordinal.Compare(a.CovenantId,b.CovenantId));return r.AsReadOnly();}
        static IReadOnlyList<AbyssAuthorityEntry022> CopyAuthorityEntries(IReadOnlyList<AbyssAuthorityEntry022> v){var r=new List<AbyssAuthorityEntry022>();if(v!=null)for(var i=0;i<v.Count;i++)r.Add(v[i]??throw new ArgumentException("Abyss authority entry cannot be null."));return r.AsReadOnly();}
        static IReadOnlyList<AbyssStepReceiptProof022> CopyStepProofs(IReadOnlyList<AbyssStepReceiptProof022> v){var r=new List<AbyssStepReceiptProof022>();if(v!=null)for(var i=0;i<v.Count;i++)r.Add(v[i]??throw new ArgumentException("Abyss step proof cannot be null."));return r.AsReadOnly();}
        static IReadOnlyList<LegacyAbyssOperationArchive022> CopyArchives(IReadOnlyList<LegacyAbyssOperationArchive022> v){var r=new List<LegacyAbyssOperationArchive022>();var seen=new HashSet<string>(StringComparer.Ordinal);if(v!=null)for(var i=0;i<v.Count;i++){var value=v[i];if(value==null||!seen.Add(value.ArchiveId))continue;r.Add(value);}return r.AsReadOnly();}
    }
}
