using System;
using System.Collections.Generic;
using SecondDimension.Gameplay.Campaign020;
using SecondDimension.Gameplay.Campaign023;

namespace SecondDimension.Presentation.Campaign020
{
 [Serializable] public sealed class CampaignManifest020 { public string contentVersion; public string title; public string baseContentVersion; public int saveFormatVersion; public int chapterBlueprintCount; public int operationalRegionCount; public int raceWorldCount; public int enemyArchetypeCount; public int recruitOriginProfileCount; public int lootEntryCount; public int materialCount; public int repeatableContractCount; public int crisisOperationCount; public int standingDefinitionCount; public string[] hardLaws; }
 [Serializable] public sealed class CampaignStepDefinition020 { public string stepId; public string kind; public string title; public string description; public string sourceId; public bool requiresCertifiedBattle; public bool committedBeforeReveal; public bool exactOnce; public bool failureCreatesRecovery; public bool consumesOperation; }
 [Serializable] public sealed class ChapterOperationBlueprint020 { public string blueprintId; public string chapterId; public string arcId; public string worldId; public string title; public string mapId; public string siegeId; public string eventId; public string diplomacyId; public string bossId; public string enemyPackId; public string lootProfileId; public string recruitPackId; public string[] materialIds; public string[] repeatableUnlockIds; public int minimumAlliedUnions; public int maximumAlliedUnions; public int maximumEnemyUnions; public CampaignStepDefinition020[] steps; public bool requiresCertifiedBattle; public bool exactOnce; public bool noConquestOnly; public bool chapterCompletionRequiresAllSteps; public bool existingEquipmentRewardRemainsAuthoritative; }
 [Serializable] public sealed class ChapterOperationBlueprintsFile020 { public ChapterOperationBlueprint020[] blueprints; }
 [Serializable] public sealed class EnemyArchetype020 { public string archetypeId; public string displayName; public string worldId; public string tacticalRole; public string[] preferredWeaponFamilies; public string[] artCategories; public string formation; public string[] forecastIdentity; public int baseTier; public int maximumTier; public bool canSurrender; public string civilianRisk; public string lootThemeId; public bool noRacewideEvilFraming; }
 [Serializable] public sealed class WorldEnemyPack020 { public string packId; public string worldId; public string displayName; public EnemyArchetype020[] archetypes; }
 [Serializable] public sealed class WorldEnemyPacksFile020 { public WorldEnemyPack020[] packs; }
 [Serializable] public sealed class RecruitOriginProfile020 { public string originProfileId; public string worldId; public string displayName; public string roleTendency; public string[] weaponFamilyCandidates; public string mysticAffinity; public string[] visualTags; public string backgroundHook; public string[] applicantUnknowns; public bool permanentWhenSigned; public bool runtimeGenerativeAi; public bool usesRecruitAutogen010; public bool signatureRecruitReplacement; }
 [Serializable] public sealed class WorldRecruitPack020 { public string packId; public string worldId; public RecruitOriginProfile020[] profiles; }
 [Serializable] public sealed class WorldRecruitPacksFile020 { public WorldRecruitPack020[] packs; }
 [Serializable] public sealed class LootEntry020 { public string entryId; public string worldId; public string displayName; public string slot; public string weaponFamilyOrArmorLine; public int minimumTier; public int maximumTier; public RarityWeights020 rarityWeights; public string[] materialIds; public string combatIdentity; public bool manualEquipOnly; public bool createsDuplicateItemCatalog; public string runtimeAuthority; }
 [Serializable] public sealed class RarityWeights020 { public int Basic; public int Common; public int Rare; public int Legendary; public int Godly; }
 [Serializable] public sealed class WorldLootProfile020 { public string profileId; public string worldId; public LootEntry020[] entries; public bool exactItemCommittedBeforeResults; public bool noAutoEquip; }
 [Serializable] public sealed class WorldLootProfilesFile020 { public WorldLootProfile020[] profiles; }
 [Serializable] public sealed class WorldMaterialDefinition020 { public string materialId; public string worldId; public string displayName; public int rarityTier; public string[] uses; public bool tradable; public bool infiniteLoopForbidden; }
 [Serializable] public sealed class WorldMaterialsFile020 { public WorldMaterialDefinition020[] materials; }
 [Serializable] public sealed class WorldGateTravelDefinition020 { public string travelId; public string worldId; public string displayName; public string gateOrHub; public string[] unlockGates; public string[] mapIds; public string timeLaw; public TravelCost020 travelCost; public bool returnToSkyhomeAlwaysAvailableAfterCommit; public bool realTimeTimer; public bool committedBeforeTransition; }
 [Serializable] public sealed class TravelCost020 { public int supplies; public string[] materials; }
 [Serializable] public sealed class WorldGateTravelFile020 { public WorldGateTravelDefinition020[] routes; }
 [Serializable] public sealed class RepeatableContract020 { public string contractId; public string worldId; public string title; public string operationType; public string objective; public int minimumNodes; public int maximumNodes; public int eventCount; public int battleCount; public string enemyPackId; public string lootProfileId; public string[] rewardMaterialIds; public int unlockedByChapterCount; public bool exactOncePerInstance; public bool boardSeedCommitted; public bool relationshipSceneCostsOperation; public bool canRemoveRecruit; }
 [Serializable] public sealed class RepeatableContractsFile020 { public RepeatableContract020[] contracts; }
 [Serializable] public sealed class WorldCrisisOperation020 { public string crisisId; public string worldId; public string title; public string type; public bool usesDefense017H; public bool usesCertifiedBattle; public string enemyPackId; public int maximumAlliedUnions; public int maximumEnemyUnions; public bool civilianObjectiveRequired; public bool failureCreatesRecovery; }
 [Serializable] public sealed class WorldCrisisOperationsFile020 { public WorldCrisisOperation020[] operations; }
 [Serializable] public sealed class StandingTier020 { public string id; public int minimumTrust; public int maximumTension; public string effect; }
 [Serializable] public sealed class WorldSettlementOutcome020 { public string worldId; public string displayName; public StandingTier020[] standingTiers; public bool worldCannotBeOwned; public bool allOutcomesRecoverable; }
 [Serializable] public sealed class WorldSettlementOutcomesFile020 { public WorldSettlementOutcome020[] outcomes; }

 public sealed class Campaign020RuleCatalogAdapter : ICampaignPlayableCatalog020, ICampaignRepeatableUnlockCatalog020
 {
   readonly List<CampaignRepeatableUnlockRule020> _repeatableUnlockRules=new List<CampaignRepeatableUnlockRule020>();
   public IReadOnlyList<CampaignRepeatableUnlockRule020> RepeatableUnlockRules=>_repeatableUnlockRules.AsReadOnly();
   readonly Dictionary<string,CampaignBlueprintRule020> _rules=new Dictionary<string,CampaignBlueprintRule020>(StringComparer.Ordinal); readonly Dictionary<string,List<string>> _repeatables=new Dictionary<string,List<string>>(StringComparer.Ordinal); readonly HashSet<string> _materials=new HashSet<string>(StringComparer.Ordinal); readonly IWorldGateOperationsCatalog023 _worldGateProofCatalog023;
   public Campaign020RuleCatalogAdapter(CampaignRegistry020 registry,IWorldGateOperationsCatalog023 worldGateProofCatalog023=null){if(registry==null)throw new ArgumentNullException(nameof(registry));_worldGateProofCatalog023=worldGateProofCatalog023??new Campaign023.Campaign023RuleCatalogAdapter(Campaign023.CampaignRegistry023.LoadFromResources());foreach(var x in registry.Blueprints.Values){var steps=new List<CampaignStepRule020>();foreach(var s in x.steps??Array.Empty<CampaignStepDefinition020>())steps.Add(new CampaignStepRule020{StepId=s.stepId,Kind=s.kind,Title=s.title,SourceId=s.sourceId,RequiresCertifiedBattle=s.requiresCertifiedBattle,ConsumesOperation=s.consumesOperation});var rule=new CampaignBlueprintRule020{BlueprintId=x.blueprintId,ChapterId=x.chapterId,ArcId=x.arcId,WorldId=x.worldId,MapId=x.mapId,SiegeId=x.siegeId,EnemyPackId=x.enemyPackId,LootProfileId=x.lootProfileId,MaterialIds=x.materialIds??Array.Empty<string>(),RepeatableUnlockIds=x.repeatableUnlockIds??Array.Empty<string>(),Steps=steps.AsReadOnly(),RequiresCertifiedBattle=x.requiresCertifiedBattle,MaximumAlliedUnions=x.maximumAlliedUnions,MaximumEnemyUnions=x.maximumEnemyUnions};if(!CampaignAdventureRules084.IsCompatible084(rule,out var boardError))throw new InvalidOperationException("Campaign 020 adventure board is unsupported: "+boardError);_rules[x.chapterId]=rule;}foreach(var c in registry.Repeatables.Values){_repeatableUnlockRules.Add(new CampaignRepeatableUnlockRule020(c.contractId,c.worldId,c.unlockedByChapterCount));if(!_repeatables.TryGetValue(c.worldId,out var list)){list=new List<string>();_repeatables[c.worldId]=list;}list.Add(c.contractId);}_repeatableUnlockRules.Sort((a,b)=>StringComparer.Ordinal.Compare(a.ContractId,b.ContractId));foreach(var m in registry.Materials.Values)_materials.Add(m.materialId);foreach(var pair in _repeatables)pair.Value.Sort(StringComparer.Ordinal);}
   public bool TryGetBlueprint(string chapterId,out CampaignBlueprintRule020 blueprint)=>_rules.TryGetValue(chapterId,out blueprint); public IReadOnlyList<string> RepeatableContractsForWorld(string worldId)=>_repeatables.TryGetValue(worldId,out var list)?list.AsReadOnly():Array.Empty<string>(); public bool IsKnownMaterial(string materialId)=>_materials.Contains(materialId); public IWorldGateOperationsCatalog023 WorldGateProofCatalog023=>_worldGateProofCatalog023;
 }
}
