using System;
using System.Collections.Generic;
using SecondDimension.Gameplay.Campaign019;

namespace SecondDimension.Presentation.Campaign019
{
 [Serializable] public sealed class CampaignManifestFile019 { public string contentVersion; public string title; public string baseContentVersion; public int chapterNarrativeCount; public int worldEventScriptCount; public int diplomacySceneCount; public int bossPlanCount; public int siegePlanCount; public int worldGameplayPackCount; public int saveFormatVersion; public string[] standardLaunchScope; public string[] developerProofScope; public string[] hardLaws; }
 [Serializable] public sealed class ChapterNarrativesFile019 { public ChapterNarrative019[] chapters; }
 [Serializable] public sealed class ChapterNarrative019 { public string chapterId; public string arcId; public string worldId; public string title; public string openingBriefing; public string guildmasterQuestion; public string civilianScene; public string factionTension; public string regionFocus; public string routeSummary; public string primaryObjectiveText; public string[] optionalObjectiveTexts; public bool battleRequired; public string battleBriefing; public string battleObjectiveType; public string victoryText; public string mixedText; public string retreatText; public string failureText; public string relationshipMemoryText; public string cityConsequenceText; public string worldTimeAdvance; public string guideTip; public string implementationStatus; public string[] canonGuardrails; }
 [Serializable] public sealed class WorldEventScriptsFile019 { public WorldEventScript019[] events; }
 [Serializable] public sealed class WorldEventChoice019 { public string id; public string label; public string knownCost; public string check; }
 [Serializable] public sealed class WorldEventScript019 { public string eventId; public string worldId; public string title; public string category; public string region; public string setup; public string actingRole; public WorldEventChoice019[] choices; public string criticalSuccess; public string success; public string mixed; public string setback; public string criticalSetback; public string worldQuestion; public bool relationshipSceneCostsOperation; public bool committedBeforeReveal; public bool canRemoveRecruit; }
 [Serializable] public sealed class DiplomacyScenesFile019 { public DiplomacyScene019[] scenes; }
 [Serializable] public sealed class DiplomacyChoice019 { public string id; public string label; public string consequence; }
 [Serializable] public sealed class DiplomacyScene019 { public string incidentId; public string worldId; public string title; public string factionId; public string factionName; public string setup; public string centralQuestion; public bool cannotResolveWorldInOneChoice; public string[] positions; public DiplomacyChoice019[] choices; public string[] outcomes; public bool mustIncludeCivilianConsequence; }
 [Serializable] public sealed class BossPhasePlansFile019 { public BossPhasePlan019[] bosses; }
 [Serializable] public sealed class BossPhase019 { public int phase; public string title; public string objective; public string battleRule; public string[] resolutionOpenings; }
 [Serializable] public sealed class BossPhasePlan019 { public string bossId; public string worldId; public string name; public string encounterRole; public string preBattleScene; public BossPhase019[] phases; public string[] postBattleResolutions; public bool executionNeverRequired; public string rewardTheme; public string objectiveHook; }
 [Serializable] public sealed class FortressOperationPlansFile019 { public FortressOperationPlan019[] sieges; }
 [Serializable] public sealed class FortressLane019 { public string id; public string name; public string purpose; }
 [Serializable] public sealed class FortressOperationPlan019 { public string siegeId; public string worldId; public string name; public string objectiveType; public string canonStatus; public string[] strategicPreparation; public FortressLane019[] lanes; public int waveCount; public int maxAlliedUnions; public int maxEnemyUnions; public string decisiveBattleTrigger; public string[] resultModes; public bool allowsSurrender; public bool civilianRules; public bool noConquestEnding; public string completionText; public string worldQuestion; }
 [Serializable] public sealed class WorldGameplayPacksFile019 { public WorldGameplayPack019[] worlds; }
 [Serializable] public sealed class WorldGameplayPack019 { public string worldId; public string name; public string fortress; public string founderRelationship; public string theme; public string centralQuestion; public string timeLaw; public string canonStatus; public string[] boardNodeFamilies; public string[] hazards; public string[] enemyUnionArchetypes; public string[] battleIdentity; public string[] equipmentThemes; public string cityUnlockIdentity; public string[] eventIds; public string[] diplomacyIncidentIds; public string[] bossIds; public string ambientDirection; public string musicDirection; public bool noConquestOnly; public string[] ordinaryPeopleRequired; }

 public sealed class CampaignRuleCatalogAdapter019 : ICampaignRuleCatalog019
 {
   readonly SecondDimension.Presentation.Campaign018.CampaignRegistry018 _base;
   readonly Dictionary<string,CampaignArcRule019> _arcs=new Dictionary<string,CampaignArcRule019>(StringComparer.Ordinal);
   readonly Dictionary<string,CampaignChapterRule019> _chapters=new Dictionary<string,CampaignChapterRule019>(StringComparer.Ordinal);
   public CampaignRuleCatalogAdapter019(SecondDimension.Presentation.Campaign018.CampaignRegistry018 value){_base=value??throw new ArgumentNullException(nameof(value));foreach(var a in _base.Arcs.Values)_arcs[a.id]=new CampaignArcRule019{ArcId=a.id,WorldId=a.worldId,ChapterIds=a.chapterIds??Array.Empty<string>(),UnlockGates=a.unlockGates??Array.Empty<string>(),RequiresOwnerApproval=a.requiresOwnerOrStoryGate};foreach(var c in _base.Chapters.Values)_chapters[c.id]=new CampaignChapterRule019{ChapterId=c.id,ArcId=c.arcId,WorldId=c.worldId,MapIds=c.mapIds??Array.Empty<string>(),SiegeId=c.siegeProfileId??string.Empty,PrimaryObjective=c.primaryObjective,GuildXp=c.rewardBundle?.guildXp??0,HallXp=c.rewardBundle?.hallXp??0,Materials=c.rewardBundle?.materials??0,BattleRequired=c.battleUsesCertifiedEngine&&(Array.Exists(c.gameplayModes??Array.Empty<string>(),x=>!string.IsNullOrWhiteSpace(x)&&x.IndexOf("BATTLE",StringComparison.OrdinalIgnoreCase)>=0)||!string.IsNullOrWhiteSpace(c.siegeProfileId)),EnemyUnionCount=string.IsNullOrWhiteSpace(c.siegeProfileId)?1:Math.Min(10,_base.Sieges[c.siegeProfileId].maxEnemyUnions),BattleId="CAMPAIGN019_BATTLE_"+c.id,StoryGates=c.unlockGates??Array.Empty<string>()};}
   public bool TryGetArc(string id,out CampaignArcRule019 arc)=>_arcs.TryGetValue(id,out arc); public bool TryGetChapter(string id,out CampaignChapterRule019 chapter)=>_chapters.TryGetValue(id,out chapter); public string LastChapterId(string arcId)=>_arcs.TryGetValue(arcId,out var a)&&a.ChapterIds.Length>0?a.ChapterIds[a.ChapterIds.Length-1]:string.Empty;
 }
}
