using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace SecondDimension.Presentation.Campaign019
{
 public sealed class CampaignRegistry019
 {
   public Campaign018.CampaignRegistry018 Base018{get;private set;} public CampaignManifestFile019 Manifest{get;private set;}
   public IReadOnlyDictionary<string,ChapterNarrative019> Chapters=>_chapters; public IReadOnlyDictionary<string,WorldEventScript019> Events=>_events; public IReadOnlyDictionary<string,DiplomacyScene019> Diplomacy=>_diplomacy; public IReadOnlyDictionary<string,BossPhasePlan019> Bosses=>_bosses; public IReadOnlyDictionary<string,FortressOperationPlan019> Sieges=>_sieges; public IReadOnlyDictionary<string,WorldGameplayPack019> Worlds=>_worlds;
   readonly Dictionary<string,ChapterNarrative019> _chapters=new Dictionary<string,ChapterNarrative019>(StringComparer.Ordinal); readonly Dictionary<string,WorldEventScript019> _events=new Dictionary<string,WorldEventScript019>(StringComparer.Ordinal); readonly Dictionary<string,DiplomacyScene019> _diplomacy=new Dictionary<string,DiplomacyScene019>(StringComparer.Ordinal); readonly Dictionary<string,BossPhasePlan019> _bosses=new Dictionary<string,BossPhasePlan019>(StringComparer.Ordinal); readonly Dictionary<string,FortressOperationPlan019> _sieges=new Dictionary<string,FortressOperationPlan019>(StringComparer.Ordinal); readonly Dictionary<string,WorldGameplayPack019> _worlds=new Dictionary<string,WorldGameplayPack019>(StringComparer.Ordinal);
   public static CampaignRegistry019 LoadFromResources(){var r=new CampaignRegistry019{Base018=Campaign018.CampaignRegistry018.LoadFromResources(),Manifest=Load<CampaignManifestFile019>("SecondDimension/Campaign019/Data/CampaignManifest019")};foreach(var x in Load<ChapterNarrativesFile019>("SecondDimension/Campaign019/Data/ChapterNarratives019").chapters??Array.Empty<ChapterNarrative019>())r._chapters.Add(x.chapterId,x);foreach(var x in Load<WorldEventScriptsFile019>("SecondDimension/Campaign019/Data/WorldEventScripts019").events??Array.Empty<WorldEventScript019>())r._events.Add(x.eventId,x);foreach(var x in Load<DiplomacyScenesFile019>("SecondDimension/Campaign019/Data/DiplomacyScenes019").scenes??Array.Empty<DiplomacyScene019>())r._diplomacy.Add(x.incidentId,x);foreach(var x in Load<BossPhasePlansFile019>("SecondDimension/Campaign019/Data/BossPhasePlans019").bosses??Array.Empty<BossPhasePlan019>())r._bosses.Add(x.bossId,x);foreach(var x in Load<FortressOperationPlansFile019>("SecondDimension/Campaign019/Data/FortressOperationPlans019").sieges??Array.Empty<FortressOperationPlan019>())r._sieges.Add(x.siegeId,x);foreach(var x in Load<WorldGameplayPacksFile019>("SecondDimension/Campaign019/Data/WorldGameplayPacks019").worlds??Array.Empty<WorldGameplayPack019>())r._worlds.Add(x.worldId,x);r.ValidateOrThrow();return r;}
   static T Load<T>(string path){var a=Resources.Load<TextAsset>(path);if(a==null)throw new InvalidOperationException("Missing Campaign 019 resource: "+path);var v=JsonUtility.FromJson<T>(a.text);if(v==null)throw new InvalidOperationException("Invalid Campaign 019 JSON: "+path);return v;}
   public void ValidateOrThrow(){if(Manifest==null||Manifest.saveFormatVersion<7||Manifest.saveFormatVersion>SecondDimension.Save.SaveEnvelopeV1.CurrentFormatVersion)throw new InvalidOperationException("Campaign 019 manifest/save version invalid");if(_chapters.Count!=Base018.Chapters.Count)throw new InvalidOperationException("Every 018 chapter requires a 019 narrative");if(_events.Count!=56||_diplomacy.Count!=28||_bosses.Count!=28||_sieges.Count!=15||_worlds.Count!=7)throw new InvalidOperationException("Campaign 019 content count mismatch");foreach(var c in Base018.Chapters.Keys)if(!_chapters.ContainsKey(c))throw new InvalidOperationException("Missing chapter narrative "+c);foreach(var n in _chapters.Values){if(n.implementationStatus!="AUTHORED_IMPLEMENTATION_READY"||string.IsNullOrWhiteSpace(n.openingBriefing)||n.openingBriefing.IndexOf("placeholder",StringComparison.OrdinalIgnoreCase)>=0)throw new InvalidOperationException("Unready chapter narrative "+n.chapterId);}foreach(var e in _events.Values)if(!e.committedBeforeReveal||e.relationshipSceneCostsOperation||e.canRemoveRecruit||e.choices==null||e.choices.Length<4)throw new InvalidOperationException("Invalid event law "+e.eventId);foreach(var d in _diplomacy.Values)if(!d.cannotResolveWorldInOneChoice||!d.mustIncludeCivilianConsequence)throw new InvalidOperationException("Invalid diplomacy law "+d.incidentId);foreach(var s in _sieges.Values){bool humane=s.noConquestEnding||s.allowsSurrender||(s.resultModes??Array.Empty<string>()).Any(x=>x.IndexOf("SURRENDER",StringComparison.OrdinalIgnoreCase)>=0||x.IndexOf("TREATY",StringComparison.OrdinalIgnoreCase)>=0||x.IndexOf("REFORM",StringComparison.OrdinalIgnoreCase)>=0);if(s.maxAlliedUnions>10||s.maxEnemyUnions>10||!humane)throw new InvalidOperationException("Invalid fortress plan "+s.siegeId);}foreach(var w in _worlds.Values)if(!w.noConquestOnly||w.ordinaryPeopleRequired==null||w.ordinaryPeopleRequired.Length<6)throw new InvalidOperationException("World lacks civilization content "+w.worldId);}
   public IEnumerable<ChapterNarrative019> ChaptersForArc(string arcId)=>_chapters.Values.Where(x=>x.arcId==arcId).OrderBy(x=>Base018.Chapters[x.chapterId].chapterNumber);
 }
}
