using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using SecondDimension.Core;
using SecondDimension.Determinism;
using SecondDimension.Gameplay.Campaign019;
using SecondDimension.Gameplay.Campaign020;
using SecondDimension.Gameplay.Campaign023;
using SecondDimension.Gameplay.GuildCity017D;
using SecondDimension.Gameplay.GuildCity017H;
using SecondDimension.Gameplay.SSSTenV4;
using SecondDimension.Gameplay.State;
namespace SecondDimension.Gameplay.Creator028
{
 public sealed class CreatorAccessCommandService028
 {
  public static string NormalizeCode(string input){if(string.IsNullOrWhiteSpace(input))return string.Empty;var b=new StringBuilder();foreach(var c in input.ToUpperInvariant())if(char.IsLetterOrDigit(c))b.Append(c);return b.ToString();}
  public static string HashNormalizedCode(string input){var n=NormalizeCode(input);if(n.Length==0)return string.Empty;using(var sha=SHA256.Create()){var d=sha.ComputeHash(Encoding.UTF8.GetBytes(n));return BitConverter.ToString(d).Replace("-",string.Empty);}}

  public Result<CampaignState> RedeemCode(CampaignState campaign,ICreatorContentCatalog028 catalog,string input,CreatorRecruitGrant028 recruitGrant=null)
  {if(!TryContext(campaign,out var city,out var strategic,out var progress,out var playable,out var state,out var error)||catalog==null)return Result<CampaignState>.Failure(error??"CREATOR028_INPUT_REQUIRED");var hash=HashNormalizedCode(input);if(string.IsNullOrEmpty(hash)||!catalog.TryGetCodeByHash(hash,out var code)||!code.Active)return Result<CampaignState>.Failure("CREATOR028_CODE_INVALID");if(state.RedeemedCodeIds.Contains(code.CodeId))return Result<CampaignState>.Success(campaign);var applied=ApplyReward(campaign,city,strategic,progress,playable,state,catalog,code.CodeId,code.Category,code.RewardId,recruitGrant);return applied;}

  /// <summary>
  /// Shared character-grant authority for persisted non-code offers. It uses the
  /// same roster, Reserve-assignment and exact-once receipt path as Creator codes
  /// without falsely recording a natural reward source as a redeemed code.
  /// </summary>
  public Result<CampaignState> GrantCharacterReward(CampaignState campaign,string sourceId,string rewardId,CreatorRecruitGrant028 recruitGrant)
  {if(string.IsNullOrWhiteSpace(sourceId)||string.IsNullOrWhiteSpace(rewardId))return Result<CampaignState>.Failure("CREATOR028_REWARD_SOURCE_REQUIRED");if(!TryContext(campaign,out var city,out var strategic,out var progress,out var playable,out var state,out var error))return Result<CampaignState>.Failure(error);return ApplyReward(campaign,city,strategic,progress,playable,state,null,sourceId,"CHARACTER",rewardId,recruitGrant,null,false);}

  public Result<CampaignState> EnterCurrentCreatorRoom(CampaignState campaign,ICreatorContentCatalog028 catalog)
  {if(!TryContext(campaign,out var city,out var strategic,out var progress,out var playable,out var state,out var error)||catalog==null)return Result<CampaignState>.Failure(error??"CREATOR028_INPUT_REQUIRED");if(state.ActiveRoomVisit!=null)return Result<CampaignState>.Success(campaign);if(!TryCurrentBoard(city,playable,out var opId,out var defId,out var boardId,out var nodeId))return Result<CampaignState>.Failure("CREATOR028_ACTIVE_MAP_REQUIRED");if(!catalog.TryGetRoomForBoard(defId,boardId,out var room))return Result<CampaignState>.Failure("CREATOR028_ROOM_NOT_AUTHORED");if(!StringComparer.Ordinal.Equals(nodeId,room.EntryNodeId))return Result<CampaignState>.Failure("CREATOR028_ROOM_NOT_AT_CURRENT_NODE");if(!string.IsNullOrWhiteSpace(room.BonusKeyId)&&!state.UnlockedRoomKeyIds.Contains(room.BonusKeyId))return Result<CampaignState>.Failure("CREATOR028_ROOM_KEY_REQUIRED");var completedKey=room.RoomId;if(state.CompletedRoomIds.Contains(completedKey))return Result<CampaignState>.Failure("CREATOR028_ROOM_REWARD_ALREADY_CLAIMED");var h=CanonicalJson.Sha256Hex(new{campaign.CampaignGuid,opId,room.RoomId,nodeId});var visit=new CreatorRoomVisitState028("CRVIS028_"+h.Substring(0,24).ToUpperInvariant(),room.RoomId,opId,defId,nodeId,room.ReturnNodeId,CreatorRoomVisitStatus028.Entered,string.Empty);var discovered=Add(state.DiscoveredRoomIds,room.RoomId);state=state.With(discoveredRoomIds:discovered,activeRoomVisit:visit,replaceActiveRoomVisit:true,lastCheckpointId:"creator_room_028_entered");return Success(campaign,city,strategic,progress,playable,state);}

  public Result<CampaignState> ResolveActiveCreatorRoom(CampaignState campaign,ICreatorContentCatalog028 catalog,CreatorRecruitGrant028 recruitGrant=null)
  {if(!TryContext(campaign,out var city,out var strategic,out var progress,out var playable,out var state,out var error)||catalog==null)return Result<CampaignState>.Failure(error??"CREATOR028_INPUT_REQUIRED");var visit=state.ActiveRoomVisit;if(visit==null)return Result<CampaignState>.Failure("CREATOR028_ACTIVE_ROOM_REQUIRED");if(!catalog.TryGetRoomForBoard(visit.BoardDefinitionId,visit.BoardDefinitionId,out var room)){room=catalog.AllRooms.FirstOrDefault(x=>StringComparer.Ordinal.Equals(x.RoomId,visit.RoomId));if(room==null)return Result<CampaignState>.Failure("CREATOR028_ROOM_UNKNOWN");}return ApplyReward(campaign,city,strategic,progress,playable,state,catalog,visit.RoomId,room.RewardKind,room.RewardId,recruitGrant,visit);}

  Result<CampaignState> ApplyReward(CampaignState campaign,GuildCityState017D city,GuildCityStrategicState017H strategic,CampaignProgressState019 progress,CampaignPlayableState020 playable,CreatorAccessState028 state,ICreatorContentCatalog028 catalog,string sourceId,string kind,string rewardId,CreatorRecruitGrant028 recruitGrant,CreatorRoomVisitState028 visit=null,bool recordSourceAsCode=true)
  {var hash=CanonicalJson.Sha256Hex(new{campaign.CampaignGuid,sourceId,kind,rewardId});var receiptId="CRREC028_"+hash.Substring(0,24).ToUpperInvariant();if(state.AppliedReceiptIds.Contains(receiptId))return Result<CampaignState>.Success(campaign);var guild=campaign.Guild;var redeemed=state.RedeemedCodeIds;var claimed=state.ClaimedInvitationIds;var content=state.UnlockedContentIds;var keys=state.UnlockedRoomKeyIds;var completed=state.CompletedRoomIds;var tokens=state.CreatorTokens;
   // Code IDs are stable authority keys, but future runtime-safe catalogs are not
   // required to reuse the historical CODE028_ prefix. A null room visit is the
   // authoritative distinction between a code redemption and a Creator Room reward.
   if(visit==null&&recordSourceAsCode)redeemed=Add(redeemed,sourceId);
   switch((kind??string.Empty).ToUpperInvariant()){
    case "RESOURCE":if(!catalog.TryGetResource(rewardId,out var rr))return Result<CampaignState>.Failure("CREATOR028_RESOURCE_UNKNOWN");var dev=guild.Development;if((rr.TreasuryXp>0||rr.HallXp>0)&&!dev.HasClaimedReward(receiptId))dev=dev.RecordBattleReward(receiptId,Math.Max(1,rr.TreasuryXp),Math.Max(1,rr.HallXp));var mats=MergeMaterials(city.Materials,rr.MaterialIds);city=city.With(materials:mats,lastCheckpointId:"creator028_resource_applied");guild=guild.With(checked(guild.TreasuryXp+rr.TreasuryXp),guild.Recruits,guild.Unions,guild.Inventory,dev).WithGuildCity(city);tokens=checked(tokens+rr.CreatorTokens);break;
    case "WEAPON":if(!catalog.TryGetWeapon(rewardId,out var wr))return Result<CampaignState>.Failure("CREATOR028_WEAPON_UNKNOWN");var inv=new List<EquipmentItemState>(guild.Inventory);var instance="CRITEM028_"+hash.Substring(0,20).ToUpperInvariant();if(!inv.Any(x=>StringComparer.Ordinal.Equals(x.InstanceId,instance)))inv.Add(new EquipmentItemState(instance,wr.WeaponId,wr.DisplayName,wr.ValidSlotIds,wr.EquipmentTags,wr.QualityId,wr.ConditionBasisPoints,false));guild=guild.With(guild.TreasuryXp,guild.Recruits,guild.Unions,inv.AsReadOnly(),guild.Development);break;
    case "CHARACTER":if(recruitGrant==null)return Result<CampaignState>.Failure("CREATOR028_RECRUIT_GRANT_REQUIRED");if(recruitGrant.Recruit.AuthorityKind!=RecruitAuthorityKind.Normal)return Result<CampaignState>.Failure("CREATOR028_PROTECTED_ACTOR_FORBIDDEN");var isSss=SssTenV4Roster090.TryGet(recruitGrant.Recruit.RecruitId,out var sssHero)||SssTenV4Roster090.TryGet(recruitGrant.Recruit.AuthoredStableRecruitId,out sssHero)||SssTenV4Roster090.TryGet(recruitGrant.Recruit.SignatureId,out sssHero)||SssTenV4Roster090.TryGet(recruitGrant.Recruit.TutorialAliasId,out sssHero);var alreadyOwned=isSss?SssTenV4Roster090.RosterContains(guild.Recruits,sssHero.HeroId):guild.Recruits.Any(x=>StringComparer.Ordinal.Equals(x.RecruitId,recruitGrant.Recruit.RecruitId));var rosterCap=isSss?310:300;if(!alreadyOwned&&guild.Recruits.Count>=rosterCap)return Result<CampaignState>.Failure("CREATOR028_ROSTER_CAP_REACHED");if(!alreadyOwned){var recruits=new List<RecruitState>(guild.Recruits){recruitGrant.Recruit};var inventory=new List<EquipmentItemState>(guild.Inventory);foreach(var item in recruitGrant.InventoryItems)if(!inventory.Any(x=>StringComparer.Ordinal.Equals(x.InstanceId,item.InstanceId)))inventory.Add(item);var assignments=new List<GuildMemberAssignmentState017D>(city.MemberAssignments){new GuildMemberAssignmentState017D(recruitGrant.Recruit.RecruitId,GuildMemberAssignmentKind017D.Reserve,string.Empty,0,0,0)};city=city.With(memberAssignments:assignments.AsReadOnly(),lastCheckpointId:"creator028_recruit_signed");guild=guild.With(guild.TreasuryXp,recruits.AsReadOnly(),guild.Unions,inventory.AsReadOnly(),guild.Development).WithGuildCity(city);}claimed=Add(claimed,rewardId);break;
    case "CONTENT":content=Add(content,rewardId);break;
    case "CHRONICLE":content=Add(content,rewardId);break;
    case "ROOM_KEY":keys=Add(keys,rewardId);break;
    default:return Result<CampaignState>.Failure("CREATOR028_REWARD_KIND_UNKNOWN");}
   var applied=Add(state.AppliedReceiptIds,receiptId);if(visit!=null)completed=Add(completed,visit.RoomId);state=state.With(redeemedCodeIds:redeemed,claimedInvitationIds:claimed,unlockedContentIds:content,unlockedRoomKeyIds:keys,completedRoomIds:completed,appliedReceiptIds:applied,creatorTokens:tokens,activeRoomVisit:null,replaceActiveRoomVisit:visit!=null,lastCheckpointId:visit==null?"creator028_code_redeemed":"creator028_room_completed");playable=playable.With(creatorAccess028:state,replaceCreatorAccess028:true,lastCheckpointId:state.LastCheckpointId);progress=progress.With(playable020:playable,replacePlayable020:true,lastCheckpointId:state.LastCheckpointId);strategic=strategic.With(campaign019:progress,replaceCampaign019:true,lastCheckpointId:state.LastCheckpointId);city=guild.GuildCity.With(strategic017H:strategic,replaceStrategic017H:true,lastCheckpointId:state.LastCheckpointId);guild=guild.WithGuildCity(city);return Result<CampaignState>.Success(campaign.With(guild,campaign.OpeningFlow));}

  static bool TryContext(CampaignState c,out GuildCityState017D city,out GuildCityStrategicState017H strategic,out CampaignProgressState019 progress,out CampaignPlayableState020 playable,out CreatorAccessState028 state,out string error){city=null;strategic=null;progress=null;playable=null;state=null;error="";if(c?.Guild?.GuildCity==null){error="CREATOR028_CAMPAIGN_REQUIRED";return false;}city=c.Guild.GuildCity;strategic=city.Strategic017H??GuildCityStrategicState017H.Default();progress=strategic.Campaign019??CampaignProgressState019.Default();playable=progress.Playable020??CampaignPlayableState020.Default();state=playable.CreatorAccess028??CreatorAccessState028.Default();return true;}
  static bool TryCurrentBoard(GuildCityState017D city,CampaignPlayableState020 playable,out string opId,out string defId,out string boardId,out string nodeId){opId=defId=boardId=nodeId=string.Empty;var wg=playable.WorldGate023?.ActiveOperation;if(wg!=null){opId=wg.OperationId;defId=wg.DefinitionId;boardId=wg.BoardId;nodeId=wg.CurrentNodeId;return true;}var ex=city.Expedition;if(ex!=null){opId=ex.ExpeditionId;defId=city.ActiveContract?.ContractId??ex.BoardId;boardId=ex.BoardId;nodeId=ex.CurrentNodeId;return true;}return false;}
  static Result<CampaignState> Success(CampaignState campaign,GuildCityState017D city,GuildCityStrategicState017H strategic,CampaignProgressState019 progress,CampaignPlayableState020 playable,CreatorAccessState028 state){playable=playable.With(creatorAccess028:state,replaceCreatorAccess028:true,lastCheckpointId:state.LastCheckpointId);progress=progress.With(playable020:playable,replacePlayable020:true,lastCheckpointId:state.LastCheckpointId);strategic=strategic.With(campaign019:progress,replaceCampaign019:true,lastCheckpointId:state.LastCheckpointId);city=city.With(strategic017H:strategic,replaceStrategic017H:true,lastCheckpointId:state.LastCheckpointId);return Result<CampaignState>.Success(campaign.With(campaign.Guild.WithGuildCity(city),campaign.OpeningFlow));}
  static IReadOnlyList<string> Add(IReadOnlyList<string> values,string value){var r=new List<string>(values??Array.Empty<string>());if(!string.IsNullOrWhiteSpace(value)&&!r.Contains(value))r.Add(value);r.Sort(StringComparer.Ordinal);return r.AsReadOnly();}
  static IReadOnlyList<GuildMaterialState017D> MergeMaterials(IReadOnlyList<GuildMaterialState017D> existing,IReadOnlyList<string> ids){var r=new List<GuildMaterialState017D>(existing??Array.Empty<GuildMaterialState017D>());if(ids!=null)foreach(var id in ids){if(string.IsNullOrWhiteSpace(id))continue;var old=r.FirstOrDefault(x=>StringComparer.Ordinal.Equals(x.MaterialId,id));if(old!=null){r.Remove(old);r.Add(old.WithAmount(old.Amount+1));}else r.Add(new GuildMaterialState017D(id,1));}r.Sort((a,b)=>StringComparer.Ordinal.Compare(a.MaterialId,b.MaterialId));return r.AsReadOnly();}
 }
}
