using System;
using System.Collections.Generic;
using SecondDimension.Gameplay.Campaign023;
namespace SecondDimension.Presentation.Campaign023
{
 [Serializable] public sealed class ManifestDto023 { public string contentVersion; public string title; public string baseContentVersion; public int saveFormatVersion; public int chapterBoardCount; public int repeatableBoardCount; public int crisisBoardCount; public int totalBoardCount; public int totalNodeCount; public int travelRouteCount; public int standingRuleCount; public int recruitmentUnlockCount; public string[] hardLaws; }
 [Serializable] public sealed class NodeDto023 { public string nodeId; public string kind; public string title; public string description; public string[] nextNodeIds; public string[] choiceIds; public int checkDifficulty; public int supplyDelta; public int fatigueDelta; public int urgencyDelta; public int threatDelta; public int trustDelta; public int tensionDelta; public int civilianSupportDelta; public int guildXp; public int hallXp; public string[] materialIds; public bool requiresCertifiedBattle; public int enemyUnionCount; public string objective; public bool optional; public string sourceId; public bool committedBeforeReveal; public bool exactOnce; public bool failureCreatesRecovery; }
 [Serializable] public sealed class BoardDto023 { public string boardId; public string definitionId; public string operationKind; public string worldId; public string title; public int minimumNodes; public int maximumNodes; public string startNodeId; public string exitNodeId; public string enemyPackId; public string lootProfileId; public bool usesStrategicDefense017H; public bool usesCertifiedBattle; public int maximumAlliedUnions; public int maximumEnemyUnions; public string canonStatus; public NodeDto023[] nodes; }
 [Serializable] public sealed class BoardRoot023 { public BoardDto023[] boards; }
 [Serializable] public sealed class TravelDto023 { public string travelId; public string worldId; public string displayName; public string gateOrHub; public string[] unlockGates; public string[] mapIds; public string timeLaw; public int supplyCost; public string[] materialIds; public bool returnToSkyhomeAlwaysAvailableAfterCommit; public bool committedBeforeTransition; public bool exactOnce; public bool realTimeTimer; }
 [Serializable] public sealed class TravelRoot023 { public TravelDto023[] routes; }
 [Serializable] public sealed class TierDto023 { public string id; public int minimumTrust; public int maximumTension; public string effect; }
 [Serializable] public sealed class StandingDto023 { public string worldId; public string displayName; public TierDto023[] tiers; public bool worldCannotBeOwned; public bool allOutcomesRecoverable; }
 [Serializable] public sealed class StandingRoot023 { public StandingDto023[] worlds; }
 [Serializable] public sealed class RecruitUnlockDto023 { public string worldId; public string displayName; public string[] compatibleExistingRaceIds; public bool nativeVisualReady; public string nativeRaceAuthority; public string[] originProfileIds; public string minimumStandingTier; public bool usesRecruitAutogen010; public bool runtimeGenerativeAi; public bool permanentWhenSigned; }
 [Serializable] public sealed class RecruitUnlockRoot023 { public RecruitUnlockDto023[] unlocks; }
 [Serializable] public sealed class RewardPolicyDto023 { public int[] repeatableConsecutiveRewardBasisPoints; public bool resetOnDifferentCompletedOperation; public string battleEquipmentRewardAuthority; public bool noIdleXp; public bool noMenuXp; public bool noWaitDay; public int travelSupplyReserveDefault; public int travelSupplyRewardPerCompletedOperation; }
 public sealed class Campaign023RuleCatalogAdapter : IWorldGateOperationsCatalog023
 {
  readonly Dictionary<string,WorldGateBoardRule023> _boards=new Dictionary<string,WorldGateBoardRule023>(StringComparer.Ordinal); readonly Dictionary<string,WorldTravelRule023> _travel=new Dictionary<string,WorldTravelRule023>(StringComparer.Ordinal); readonly Dictionary<string,WorldStandingRule023> _standing=new Dictionary<string,WorldStandingRule023>(StringComparer.Ordinal); readonly Dictionary<string,RecruitUnlockRule023> _recruits=new Dictionary<string,RecruitUnlockRule023>(StringComparer.Ordinal);
  public Campaign023RuleCatalogAdapter(CampaignRegistry023 r){foreach(var b in r.Boards.Values){var nodes=new List<WorldGateNodeRule023>();foreach(var n in b.nodes??Array.Empty<NodeDto023>())nodes.Add(new WorldGateNodeRule023{NodeId=n.nodeId,Kind=n.kind,Title=n.title,Description=n.description,NextNodeIds=n.nextNodeIds??Array.Empty<string>(),ChoiceIds=n.choiceIds??Array.Empty<string>(),CheckDifficulty=n.checkDifficulty,SupplyDelta=n.supplyDelta,FatigueDelta=n.fatigueDelta,UrgencyDelta=n.urgencyDelta,ThreatDelta=n.threatDelta,TrustDelta=n.trustDelta,TensionDelta=n.tensionDelta,CivilianSupportDelta=n.civilianSupportDelta,GuildXp=n.guildXp,HallXp=n.hallXp,MaterialIds=n.materialIds??Array.Empty<string>(),RequiresCertifiedBattle=n.requiresCertifiedBattle,EnemyUnionCount=n.enemyUnionCount,Objective=n.objective,Optional=n.optional,SourceId=n.sourceId});var rule=new WorldGateBoardRule023{BoardId=b.boardId,DefinitionId=b.definitionId,OperationKind=b.operationKind,WorldId=b.worldId,Title=b.title,StartNodeId=b.startNodeId,ExitNodeId=b.exitNodeId,EnemyPackId=b.enemyPackId,LootProfileId=b.lootProfileId,UsesStrategicDefense017H=b.usesStrategicDefense017H,UsesCertifiedBattle=b.usesCertifiedBattle,MaximumAlliedUnions=b.maximumAlliedUnions,MaximumEnemyUnions=b.maximumEnemyUnions,Nodes=nodes.AsReadOnly()};if(!BoardAdventureRules084.IsCompatible084(rule,out var boardError))throw new InvalidOperationException("Campaign 023 adventure board is unsupported: "+boardError);_boards[b.definitionId]=rule;}foreach(var t in r.Travel.Values)_travel[t.worldId]=new WorldTravelRule023{TravelId=t.travelId,WorldId=t.worldId,DisplayName=t.displayName,GateOrHub=t.gateOrHub,UnlockGates=t.unlockGates??Array.Empty<string>(),SupplyCost=t.supplyCost,MaterialIds=t.materialIds??Array.Empty<string>(),ReturnToSkyhomeAlwaysAvailableAfterCommit=t.returnToSkyhomeAlwaysAvailableAfterCommit};foreach(var w in r.Standing.Values){var ids=new List<string>();foreach(var tier in w.tiers??Array.Empty<TierDto023>())ids.Add(tier.id);_standing[w.worldId]=new WorldStandingRule023{WorldId=w.worldId,DisplayName=w.displayName,TierIds=ids.AsReadOnly()};}foreach(var u in r.RecruitUnlocks.Values)_recruits[u.worldId]=new RecruitUnlockRule023{WorldId=u.worldId,DisplayName=u.displayName,OriginProfileIds=u.originProfileIds??Array.Empty<string>(),MinimumStandingTier=u.minimumStandingTier,NativeVisualReady=u.nativeVisualReady};RewardPolicy=new WorldGateRewardPolicy023{RepeatableConsecutiveRewardBasisPoints=r.RewardPolicy.repeatableConsecutiveRewardBasisPoints??Array.Empty<int>(),ResetOnDifferentCompletedOperation=r.RewardPolicy.resetOnDifferentCompletedOperation,TravelSupplyReserveDefault=r.RewardPolicy.travelSupplyReserveDefault,TravelSupplyRewardPerCompletedOperation=r.RewardPolicy.travelSupplyRewardPerCompletedOperation};}
  public bool TryGetBoard(string id,out WorldGateBoardRule023 b)=>_boards.TryGetValue(id,out b); public bool TryGetTravel(string id,out WorldTravelRule023 t)=>_travel.TryGetValue(id,out t); public bool TryGetStanding(string id,out WorldStandingRule023 s)=>_standing.TryGetValue(id,out s); public bool TryGetRecruitUnlock(string id,out RecruitUnlockRule023 u)=>_recruits.TryGetValue(id,out u); public WorldGateRewardPolicy023 RewardPolicy{get;} public IReadOnlyList<WorldGateBoardRule023> AllBoards=>new List<WorldGateBoardRule023>(_boards.Values).AsReadOnly();
 }
}
