using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using UnityEngine;
namespace SecondDimension.Presentation.Campaign023
{
 public sealed class CampaignRegistry023
 {
  public ManifestDto023 Manifest{get;private set;} public IReadOnlyDictionary<string,BoardDto023> Boards{get;private set;} public IReadOnlyDictionary<string,TravelDto023> Travel{get;private set;} public IReadOnlyDictionary<string,StandingDto023> Standing{get;private set;} public IReadOnlyDictionary<string,RecruitUnlockDto023> RecruitUnlocks{get;private set;} public RewardPolicyDto023 RewardPolicy{get;private set;}
  public static CampaignRegistry023 LoadFromResources(){var r=new CampaignRegistry023();r.Manifest=Load<ManifestDto023>("SecondDimension/Campaign023/Data/CampaignManifest023");r.Boards=(Load<BoardRoot023>("SecondDimension/Campaign023/Data/CampaignBoardBlueprints023").boards??Array.Empty<BoardDto023>()).ToDictionary(x=>x.definitionId,StringComparer.Ordinal);r.Travel=(Load<TravelRoot023>("SecondDimension/Campaign023/Data/WorldTravelRoutes023").routes??Array.Empty<TravelDto023>()).ToDictionary(x=>x.worldId,StringComparer.Ordinal);r.Standing=(Load<StandingRoot023>("SecondDimension/Campaign023/Data/WorldStandingRules023").worlds??Array.Empty<StandingDto023>()).ToDictionary(x=>x.worldId,StringComparer.Ordinal);r.RecruitUnlocks=(Load<RecruitUnlockRoot023>("SecondDimension/Campaign023/Data/RecruitmentWorldUnlocks023").unlocks??Array.Empty<RecruitUnlockDto023>()).ToDictionary(x=>x.worldId,StringComparer.Ordinal);r.RewardPolicy=Load<RewardPolicyDto023>("SecondDimension/Campaign023/Data/OperationRewardPolicy023");r.ValidateOrThrow();return r;}
  public void ValidateOrThrow(){if(Manifest==null||Manifest.saveFormatVersion!=SecondDimension.Save.SaveEnvelopeV1.CurrentFormatVersion||Manifest.totalBoardCount!=130)throw new InvalidOperationException("Campaign 023 manifest/save mismatch.");if(Boards.Count!=130||Travel.Count!=8||Standing.Count!=8||RecruitUnlocks.Count!=8)throw new InvalidOperationException("Campaign 023 content counts invalid.");var nodeIds=new HashSet<string>(StringComparer.Ordinal);foreach(var b in Boards.Values){if(b.nodes==null||b.nodes.Length<10||b.maximumAlliedUnions>10||b.maximumEnemyUnions>10)throw new InvalidOperationException("Campaign 023 board invalid: "+b.definitionId);var ids=new HashSet<string>((b.nodes??Array.Empty<NodeDto023>()).Select(x=>x.nodeId),StringComparer.Ordinal);if(!ids.Contains(b.startNodeId)||!ids.Contains(b.exitNodeId))throw new InvalidOperationException("Campaign 023 board endpoints invalid: "+b.definitionId);foreach(var n in b.nodes){if(!n.committedBeforeReveal||!n.exactOnce||!n.failureCreatesRecovery)throw new InvalidOperationException("Campaign 023 node law failed: "+n.nodeId);if(!nodeIds.Add(n.nodeId))throw new InvalidOperationException("Campaign 023 duplicate node: "+n.nodeId);foreach(var next in n.nextNodeIds??Array.Empty<string>())if(!ids.Contains(next))throw new InvalidOperationException("Campaign 023 next-node reference invalid: "+n.nodeId);if(n.requiresCertifiedBattle&&n.enemyUnionCount>10)throw new InvalidOperationException("Campaign 023 enemy Union cap failed: "+n.nodeId);}}if(RewardPolicy.battleEquipmentRewardAuthority!="EXISTING_M2_REWARD_RECEIPT"||!RewardPolicy.noIdleXp||!RewardPolicy.noMenuXp||!RewardPolicy.noWaitDay)throw new InvalidOperationException("Campaign 023 reward law failed.");if(RecruitUnlocks.Values.Any(x=>!x.usesRecruitAutogen010||x.runtimeGenerativeAi||!x.permanentWhenSigned))throw new InvalidOperationException("Campaign 023 recruit law failed.");}
  static T Load<T>(string path){var a=Resources.Load<TextAsset>(path);if(a==null)throw new InvalidOperationException("Missing Campaign 023 resource: "+path);var v=JsonConvert.DeserializeObject<T>(a.text);if(v==null)throw new InvalidOperationException("Invalid Campaign 023 resource: "+path);return v;}
 }
}
