using System.Collections.Generic;
namespace SecondDimension.Presentation.Campaign023
{
 public sealed class BoardView023 { public string DefinitionId; public string WorldId; public string WorldName; public string Title; public string Kind; public string PlayerKind; public string Objective; public string RewardPreview; public int NodeCount; public int TreasureCardCount; public int DiceCardCount; public int StoryCardCount; public int BattleCardCount; public int RecruitContactCount; public bool Available; public bool UsesBattle; public bool IsCurrentStoryBoard; }
 public sealed class ChoiceView023 { public string ChoiceId; public string Label; public string StableOrderKey; }
 public sealed class ExpeditionRouteCardView089 { public string CardId; public string Category; public string VisualCategoryKey; public string VisualResourcePath; public string Title; public string Description; public string RiskLabel; public string Odds; public string OutcomePreview; public int SuccessBasisPoints; public string RewardPreview; public string RouteLabel; public string RecruitStableId; public string RecruitName; public string RecruitRank; public bool LockedToBattle; public bool IsEncounterRound; public bool RequiresCertifiedBattle; public int EnemyUnionCount; public int TreasuryXpCost; public long TreasuryXpBalance; public bool CanChoose; public string LockedReason; public string PermanentHeroName; public string PermanentHeroEffectKind; public int PermanentHeroCheckModifier; }
 public sealed class AdventureTrackTileView023 { public string NodeId; public int AuthoredOrder; public int SpaceNumber; public int BranchIndex; public int BranchCount; public string State; public string RevealedLabel; }
 public sealed class NodeView023 { public string NodeId; public string Kind; public string RoomKind; public string RoomTitle; public string Title; public string Description; public string StoryFlavor; public string Objective; public string RewardPreview; public IReadOnlyList<string> Choices; public IReadOnlyList<ChoiceView023> ChoiceViews; public int Difficulty; public bool RequiresBattle; public string IconResource; }
 public sealed class StandingView023 { public string WorldId; public string DisplayName; public string Tier; public int Trust; public int Tension; public int CivilianSupport; public bool Unlocked; public int TravelSupplyCost; public bool CanAffordTravel; }
  public sealed class CampaignWorldGatePresentationState023 { public bool IsAvailable; public string Error; public string CurrentWorldId; public string CurrentWorldName; public int TravelSupplies; public string ActiveOperationId; public string ActiveDefinitionId; public string ActiveBoardTitle; public string ActiveOperationKind; public string ActiveStatus; public string BoardObjective; public int Supplies; public int Fatigue; public int Urgency; public int Threat; public int CompletedNodes; public int TotalNodes; public int AdventureTrackPhase; public string PendingReceiptId; public string PendingOutcomeTitle; public string PendingDice; public string PendingReward; public bool PendingHasCheck; public int PendingDieOne; public int PendingDieTwo; public int PendingModifier; public int PendingTotal; public int PendingDifficulty; public string PendingChoiceLabel; public bool PendingIsEncounterRound; public bool PendingRequiresCertifiedBattle; public bool HasLastAppliedRoom; public string LastAppliedRoomTitle; public string LastAppliedOutcomeTitle; public string LastAppliedReward; public string LastAppliedChoiceLabel; public string ExistingRewardId; public bool LegacyRecoveryRequired; public NodeView023 CurrentNode; public IReadOnlyList<AdventureTrackTileView023> AdventureTiles; public IReadOnlyList<BoardView023> Boards; public IReadOnlyList<StandingView023> Standings; public IReadOnlyList<string> UnlockedRecruitOriginIds; public IReadOnlyList<ExpeditionRouteCardView089> RouteCards; public int DeckDrawPileCount; public int DeckDiscardCount; public int DeckBanishedCount; public int DeckMomentum; public int DeckChoiceRound; public int DeckMinimumChoiceRounds; public int DeckProgressionTier; public int DeckCardsPerNode; public IReadOnlyList<string> DeckUnlockedCategoryIds; public IReadOnlyList<string> DeckModifierLabels; public IReadOnlyList<string> DeckRemainingCompositionLabels; public IReadOnlyList<string> DeckDiscardCompositionLabels; public IReadOnlyList<string> ExpeditionRecruitLeadIds; public bool ExpeditionDeckTutorialSeen; public IReadOnlyList<string> ExpeditionDeckTutorialSteps; public string PendingCardCategory; public string PendingCardTitle; public string PendingCardVisualResourcePath; public bool PendingChestHasReward092; public string PendingChestItemVisualId092; public string PendingChestItemName092; public string PendingChestRarityId092; public string PendingChestRewardCopy092; }
 public interface ICampaignWorldGatePresentationCoordinator023
 {
   CampaignWorldGatePresentationState023 CampaignWorldGate023{get;} M1CommandResult BeginWorldGateOperation023(string definitionId); M1CommandResult CommitWorldGateChoice023(string choiceId); M1CommandResult CommitAutomaticWorldGateRoom023(); M1CommandResult ApplyWorldGateReceipt023(); M1CommandResult EnterWorldGateBattle023(); M1CommandResult FinalizeWorldGateOperation023(); M1CommandResult TravelWorldGate023(string worldId); M1CommandResult RecoverLegacyWorldGateQuest023();
 }
 public interface IExpeditionDeckPresentationCoordinator089
 {
  M1CommandResult CommitExpeditionRouteCard089(string cardId);
  M1CommandResult EnterExpeditionCardBattle089();
  M1CommandResult AcknowledgeExpeditionDeckTutorial089();
 }
}
