using System;
using System.Linq;
using UnityEngine;
namespace SecondDimension.Presentation
{
 public sealed partial class M1FlowPresenter
 {
  void BuildGuildCityWorldGateLegacy023(Transform body,Campaign023.ICampaignWorldGatePresentationCoordinator023 c,Campaign023.CampaignWorldGatePresentationState023 s)
  {if(s==null||!s.IsAvailable){AddMessagePanel(body,"WORLD GATE OPERATIONS 023",s?.Error??"World Gate authority unavailable.",RuntimeUi.Warning);return;}AddMessagePanel(body,"WORLD GATE EXPEDITIONS","All 82 story chapters, 32 repeatable contracts, and 16 world crises now use committed board routes, 2d6 checks, camps, diplomacy, resources, certified Union battles, exact return state, and anti-farm rewards. No rerolls, wait-day costs, or duplicate equipment rewards.",RuntimeUi.Accent);AddMessagePanel(body,"CURRENT WORLD",s.CurrentWorldId+" • TRAVEL SUPPLIES "+s.TravelSupplies+" • UNLOCKED RECRUIT ORIGINS "+(s.UnlockedRecruitOriginIds?.Count??0),RuntimeUi.ButtonNormal);
   if(!string.IsNullOrWhiteSpace(s.ActiveOperationId)){AddMessagePanel(body,"ACTIVE WORLD GATE OPERATION",s.ActiveDefinitionId+" • "+s.ActiveStatus+" • NODES COMPLETE "+s.CompletedNodes+"\nSUPPLIES "+s.Supplies+" • FATIGUE "+s.Fatigue+" • URGENCY "+s.Urgency+" • THREAT "+s.Threat+(string.IsNullOrWhiteSpace(s.ExistingRewardId)?"":"\nEXISTING BATTLE REWARD LINKED: "+s.ExistingRewardId),RuntimeUi.Warning);if(s.CurrentNode!=null){var panel=AddMessagePanel(body,s.CurrentNode.Title,s.CurrentNode.Kind+" • "+(s.CurrentNode.Difficulty>0?"CHECK "+s.CurrentNode.Difficulty+" • ":"")+(s.CurrentNode.RequiresBattle?"CERTIFIED UNION BATTLE\n":"\n")+s.CurrentNode.Description,RuntimeUi.ButtonNormal);if(!string.IsNullOrWhiteSpace(s.PendingReceiptId))RuntimeUi.AddButton(panel,"Apply World Gate receipt 023","APPLY EXACT-ONCE RESULT",()=>RunGuildCityCommand017D(c.ApplyWorldGateReceipt023),122f,RuntimeUi.Positive);else if(s.CurrentNode.RequiresBattle&&s.ActiveStatus=="Active")RuntimeUi.AddButton(panel,"Enter World Gate battle 023","ENTER CERTIFIED UNION BATTLE",()=>{var r=c.EnterWorldGateBattle023();_localStatus=r.Message;_localStatusPositive=r.Succeeded;if(r.Succeeded)Navigate(M1Screen.Battle);else BuildCurrentScreen();},126f,RuntimeUi.Accent);else if(s.ActiveStatus=="ReadyToFinalize")RuntimeUi.AddButton(panel,"Finalize World Gate operation 023","FINALIZE OPERATION",()=>RunGuildCityCommand017D(c.FinalizeWorldGateOperation023),126f,RuntimeUi.Positive);else foreach(var choice in s.CurrentNode.Choices??Array.Empty<string>())RuntimeUi.AddButton(panel,"World Gate choice "+choice,choice.Replace('_',' '),()=>RunGuildCityCommand017D(()=>c.CommitWorldGateChoice023(choice)),118f,RuntimeUi.Accent);}}
   else{foreach(var b in (s.Boards??Array.Empty<Campaign023.BoardView023>()).Where(x=>x.Available).Take(18)){var panel=AddMessagePanel(body,b.Title,b.Kind+" • "+b.WorldId+" • "+b.NodeCount+" NODES"+(b.UsesBattle?" • CERTIFIED BATTLE":""),RuntimeUi.ButtonNormal);RuntimeUi.AddButton(panel,"Begin World Gate board "+b.DefinitionId,"COMMIT BOARD",()=>RunGuildCityCommand017D(()=>c.BeginWorldGateOperation023(b.DefinitionId)),118f,RuntimeUi.Accent);}}
   AddMessagePanel(body,"WORLD STANDING",string.Join("\n",(s.Standings??Array.Empty<Campaign023.StandingView023>()).Select(x=>(x.Unlocked?"OPEN • ":"LOCKED • ")+x.DisplayName+" — "+x.Tier+" • TRUST "+x.Trust+" • TENSION "+x.Tension+" • CIVILIANS "+x.CivilianSupport)),RuntimeUi.ButtonNormal);foreach(var w in (s.Standings??Array.Empty<Campaign023.StandingView023>()).Where(x=>x.Unlocked&&x.WorldId!=s.CurrentWorldId).Take(8))RuntimeUi.AddButton(body,"Travel World Gate "+w.WorldId,"TRAVEL TO "+w.DisplayName.ToUpperInvariant(),()=>RunGuildCityCommand017D(()=>c.TravelWorldGate023(w.WorldId)),118f,RuntimeUi.Accent);if(s.CurrentWorldId!="SKYHOME")RuntimeUi.AddButton(body,"Return Skyhome World Gate 023","RETURN TO SKYHOME",()=>RunGuildCityCommand017D(()=>c.TravelWorldGate023("SKYHOME")),118f,RuntimeUi.Positive);
  }
 }
}
