using System;
namespace SecondDimension.Presentation.Campaign021
{
 [Serializable] public sealed class CampaignManifest021 { public string contentVersion; public string title; public string baseContentVersion; public int saveFormatVersion; public int worldThemeCount; public int enemyPresentationCount; public int bossPresentationCount; public int bossPhasePresentationCount; public int recruitOriginPresentationCount; public int lootPresentationCount; public int materialPresentationCount; public int operationPresentationCount; public int travelPresentationCount; public int settlementPresentationCount; public int chapterPresentationCount; public int audioCueCount; public string[] hardLaws; }
 [Serializable] public sealed class WorldPresentationTheme021 { public string themeId; public string worldId; public string displayName; public string backgroundResource; public string frameResource; public string ambientAudioCueId; public string travelAudioCueId; public string battleIntroAudioCueId; public string victoryAudioCueId; public string[] paletteTags; public string[] uiMotifs; public string materialLanguage; public string weatherMotion; public string cameraEstablishing; public bool supportsPc; public bool supportsIphoneLandscape; public bool noBakedDynamicText; }
 [Serializable] public sealed class WorldPresentationThemesFile021 { public WorldPresentationTheme021[] themes; }
 [Serializable] public sealed class EnemyPresentationProfile021 { public string profileId; public string archetypeId; public string worldId; public string displayName; public string emblemResource; public string modularBodyRecipe; public string poseFamily; public string weaponAnimationFamily; public string mysticPresentationFamily; public string vfxFamily; public string audioCueId; public string cameraProfile; public string lodPolicy; public string[] silhouetteTags; public string[] paletteTags; public string surrenderPresentation; public string reformPresentation; public string downedPresentation; public bool usesExistingArtAuthority; public bool noRacewideEvilFraming; public string productionStatus; }
 [Serializable] public sealed class EnemyPresentationProfilesFile021 { public EnemyPresentationProfile021[] profiles; }
 [Serializable] public sealed class BossPhasePresentation021 { public int phase; public string title; public string objective; public string cameraProfile; public string vfxFamily; public string audioCueId; public string[] resolutionOpenings; public string battleRule; public string transitionPresentation; }
 [Serializable] public sealed class BossPresentationProfile021 { public string profileId; public string bossId; public string worldId; public string displayName; public string encounterRole; public string emblemResource; public string introAudioCueId; public string arenaThemeId; public string preBattleScene; public BossPhasePresentation021[] phases; public string[] postBattleResolutions; public bool executionNeverRequired; public string rewardTheme; public string objectiveHook; public string surrenderCamera; public string exposeCamera; public string negotiationCamera; public string rescueCamera; public bool usesCertifiedUnionBattle; public string productionStatus; }
 [Serializable] public sealed class BossPresentationProfilesFile021 { public BossPresentationProfile021[] profiles; }
 [Serializable] public sealed class RecruitOriginPresentation021 { public string presentationId; public string originProfileId; public string worldId; public string displayName; public string emblemResource; public string[] autogen010VisualTags; public string outfitSilhouette; public string armorWeight; public string[] worldPaletteTags; public string[] weaponPropCandidates; public string[] motionSetCandidates; public string mysticAffinity; public string portraitLighting; public string backgroundHook; public bool usesRecruitAutogen010; public bool permanentWhenSigned; public bool runtimeGenerativeAi; public bool borrowsNamedCharacterIdentity; public string productionStatus; }
 [Serializable] public sealed class RecruitOriginPresentationsFile021 { public RecruitOriginPresentation021[] profiles; }
 [Serializable] public sealed class LootPresentationBinding021 { public string bindingId; public string entryId; public string worldId; public string displayName; public string iconResource; public string revealVfxFamily; public string revealAudioCueId; public string rarityFramePolicy; public string comparisonBadge; public bool manualEquipOnly; public string existingRewardAuthority; public bool createsDuplicateItemCatalog; public string productionStatus; }
 [Serializable] public sealed class LootPresentationBindingsFile021 { public LootPresentationBinding021[] bindings; }
 [Serializable] public sealed class MaterialPresentationBinding021 { public string bindingId; public string materialId; public string worldId; public string displayName; public string iconResource; public string pickupAudioCueId; public int rarityTier; public string[] uses; public bool tradable; public bool infiniteLoopForbidden; public string productionStatus; }
 [Serializable] public sealed class MaterialPresentationBindingsFile021 { public MaterialPresentationBinding021[] bindings; }
 [Serializable] public sealed class OperationPresentationBinding021 { public string bindingId; public string sourceId; public string sourceType; public string worldId; public string title; public string iconResource; public string worldThemeId; public string briefingAudioCueId; public string completionAudioCueId; public string cardFrameResource; public bool exactOncePerInstance; public string productionStatus; }
 [Serializable] public sealed class OperationPresentationBindingsFile021 { public OperationPresentationBinding021[] bindings; }
 [Serializable] public sealed class TravelPresentationBinding021 { public string bindingId; public string travelId; public string worldId; public string displayName; public string iconResource; public string backgroundResource; public string travelAudioCueId; public string timeLaw; public bool committedBeforeTransition; public bool realTimeTimer; public string productionStatus; }
 [Serializable] public sealed class TravelPresentationBindingsFile021 { public TravelPresentationBinding021[] bindings; }
 [Serializable] public sealed class SettlementPresentationBinding021 { public string bindingId; public string worldId; public string displayName; public string iconResource; public string[] standingTierIds; public bool worldCannotBeOwned; public bool allOutcomesRecoverable; public string productionStatus; }
 [Serializable] public sealed class SettlementPresentationBindingsFile021 { public SettlementPresentationBinding021[] bindings; }
 [Serializable] public sealed class ChapterPresentationBinding021 { public string bindingId; public string chapterId; public string arcId; public string worldId; public string title; public string worldThemeId; public string titleBackgroundResource; public string frameResource; public string briefingAudioCueId; public string battleIntroAudioCueId; public string victoryAudioCueId; public string mapId; public string enemyPackId; public string bossId; public string lootProfileId; public string openingBriefing; public string battleBriefing; public string victoryText; public string mixedText; public string retreatText; public string failureText; public string relationshipMemoryText; public string cityConsequenceText; public bool noBakedDynamicText; public string productionStatus; }
 [Serializable] public sealed class ChapterPresentationBindingsFile021 { public ChapterPresentationBinding021[] bindings; }
 [Serializable] public sealed class AudioCueDefinition021 { public string cueId; public string worldId; public string category; public string resourcePath; public bool loop; public float defaultVolume; public string productionStatus; }
 [Serializable] public sealed class AudioCueManifestFile021 { public AudioCueDefinition021[] cues; }
}
