using System; using System.Collections.Generic; using System.Linq; using UnityEngine;
namespace SecondDimension.Presentation.Campaign021
{
 public sealed class CampaignPresentationRegistry021
 {
  public Campaign020.CampaignRegistry020 Base020{get;private set;} public CampaignManifest021 Manifest{get;private set;}
  public IReadOnlyDictionary<string,WorldPresentationTheme021> Worlds=>_worlds; public IReadOnlyDictionary<string,EnemyPresentationProfile021> Enemies=>_enemies; public IReadOnlyDictionary<string,BossPresentationProfile021> Bosses=>_bosses; public IReadOnlyDictionary<string,RecruitOriginPresentation021> Recruits=>_recruits; public IReadOnlyDictionary<string,LootPresentationBinding021> Loot=>_loot; public IReadOnlyDictionary<string,MaterialPresentationBinding021> Materials=>_materials; public IReadOnlyDictionary<string,OperationPresentationBinding021> Operations=>_operations; public IReadOnlyDictionary<string,TravelPresentationBinding021> Travel=>_travel; public IReadOnlyDictionary<string,SettlementPresentationBinding021> Settlements=>_settlements; public IReadOnlyDictionary<string,ChapterPresentationBinding021> Chapters=>_chapters; public IReadOnlyDictionary<string,AudioCueDefinition021> Audio=>_audio;
  readonly Dictionary<string,WorldPresentationTheme021> _worlds=new Dictionary<string,WorldPresentationTheme021>(StringComparer.Ordinal); readonly Dictionary<string,EnemyPresentationProfile021> _enemies=new Dictionary<string,EnemyPresentationProfile021>(StringComparer.Ordinal); readonly Dictionary<string,BossPresentationProfile021> _bosses=new Dictionary<string,BossPresentationProfile021>(StringComparer.Ordinal); readonly Dictionary<string,RecruitOriginPresentation021> _recruits=new Dictionary<string,RecruitOriginPresentation021>(StringComparer.Ordinal); readonly Dictionary<string,LootPresentationBinding021> _loot=new Dictionary<string,LootPresentationBinding021>(StringComparer.Ordinal); readonly Dictionary<string,MaterialPresentationBinding021> _materials=new Dictionary<string,MaterialPresentationBinding021>(StringComparer.Ordinal); readonly Dictionary<string,OperationPresentationBinding021> _operations=new Dictionary<string,OperationPresentationBinding021>(StringComparer.Ordinal); readonly Dictionary<string,TravelPresentationBinding021> _travel=new Dictionary<string,TravelPresentationBinding021>(StringComparer.Ordinal); readonly Dictionary<string,SettlementPresentationBinding021> _settlements=new Dictionary<string,SettlementPresentationBinding021>(StringComparer.Ordinal); readonly Dictionary<string,ChapterPresentationBinding021> _chapters=new Dictionary<string,ChapterPresentationBinding021>(StringComparer.Ordinal); readonly Dictionary<string,AudioCueDefinition021> _audio=new Dictionary<string,AudioCueDefinition021>(StringComparer.Ordinal);
  public static CampaignPresentationRegistry021 LoadFromResources(){var r=new CampaignPresentationRegistry021{Base020=Campaign020.CampaignRegistry020.LoadFromResources(),Manifest=Load<CampaignManifest021>("SecondDimension/Campaign021/Data/CampaignManifest021")};Add(r._worlds,Load<WorldPresentationThemesFile021>("SecondDimension/Campaign021/Data/WorldPresentationThemes021").themes,x=>x.worldId);Add(r._enemies,Load<EnemyPresentationProfilesFile021>("SecondDimension/Campaign021/Data/EnemyPresentationProfiles021").profiles,x=>x.archetypeId);Add(r._bosses,Load<BossPresentationProfilesFile021>("SecondDimension/Campaign021/Data/BossPresentationProfiles021").profiles,x=>x.bossId);Add(r._recruits,Load<RecruitOriginPresentationsFile021>("SecondDimension/Campaign021/Data/RecruitOriginPresentation021").profiles,x=>x.originProfileId);Add(r._loot,Load<LootPresentationBindingsFile021>("SecondDimension/Campaign021/Data/LootPresentationBindings021").bindings,x=>x.entryId);Add(r._materials,Load<MaterialPresentationBindingsFile021>("SecondDimension/Campaign021/Data/MaterialPresentationBindings021").bindings,x=>x.materialId);Add(r._operations,Load<OperationPresentationBindingsFile021>("SecondDimension/Campaign021/Data/OperationPresentationBindings021").bindings,x=>x.sourceId);Add(r._travel,Load<TravelPresentationBindingsFile021>("SecondDimension/Campaign021/Data/TravelPresentationBindings021").bindings,x=>x.travelId);Add(r._settlements,Load<SettlementPresentationBindingsFile021>("SecondDimension/Campaign021/Data/SettlementPresentationBindings021").bindings,x=>x.worldId);Add(r._chapters,Load<ChapterPresentationBindingsFile021>("SecondDimension/Campaign021/Data/ChapterPresentationBindings021").bindings,x=>x.chapterId);Add(r._audio,Load<AudioCueManifestFile021>("SecondDimension/Campaign021/Data/AudioCueManifest021").cues,x=>x.cueId);r.ValidateOrThrow();return r;}
  static T Load<T>(string path){var a=Resources.Load<TextAsset>(path);if(a==null)throw new InvalidOperationException("Missing Campaign 021 resource: "+path);var v=JsonUtility.FromJson<T>(a.text);if(v==null)throw new InvalidOperationException("Invalid Campaign 021 JSON: "+path);return v;}
  static void Add<T>(Dictionary<string,T> d,T[] values,Func<T,string> key){foreach(var x in values??Array.Empty<T>()){var k=key(x);if(string.IsNullOrWhiteSpace(k)||d.ContainsKey(k))throw new InvalidOperationException("Campaign 021 duplicate/blank ID: "+k);d.Add(k,x);}}
  public void ValidateOrThrow(){if(Manifest==null||Manifest.saveFormatVersion<8||Manifest.saveFormatVersion>SecondDimension.Save.SaveEnvelopeV1.CurrentFormatVersion||Manifest.baseContentVersion!="CAMPAIGN_PLAYABLE_OPERATIONS_020_1.0")throw new InvalidOperationException("Campaign 021 manifest/base invalid");if(_worlds.Count!=8||_enemies.Count!=64||_bosses.Count!=28||_recruits.Count!=56||_loot.Count!=96||_materials.Count!=48||_operations.Count!=48||_travel.Count!=8||_settlements.Count!=9||_chapters.Count!=82||_audio.Count!=60)throw new InvalidOperationException("Campaign 021 content counts invalid");foreach(var w in _worlds.Values)if(!w.noBakedDynamicText||!w.supportsPc||!w.supportsIphoneLandscape)throw new InvalidOperationException("World presentation law failed: "+w.worldId);foreach(var e in _enemies.Values)if(!e.usesExistingArtAuthority||!e.noRacewideEvilFraming||string.IsNullOrWhiteSpace(e.emblemResource))throw new InvalidOperationException("Enemy presentation law failed: "+e.archetypeId);foreach(var b in _bosses.Values)if(!b.usesCertifiedUnionBattle||!b.executionNeverRequired||b.phases==null||b.phases.Length<2)throw new InvalidOperationException("Boss presentation law failed: "+b.bossId);foreach(var r in _recruits.Values)if(!r.usesRecruitAutogen010||!r.permanentWhenSigned||r.runtimeGenerativeAi||r.borrowsNamedCharacterIdentity)throw new InvalidOperationException("Recruit presentation law failed: "+r.originProfileId);foreach(var l in _loot.Values)if(!l.manualEquipOnly||l.createsDuplicateItemCatalog)throw new InvalidOperationException("Loot presentation law failed: "+l.entryId);foreach(var c in _chapters.Values)if(!c.noBakedDynamicText||!Base020.Blueprints.ContainsKey(c.chapterId))throw new InvalidOperationException("Chapter presentation law failed: "+c.chapterId);}
 }
}
