using System; using System.Collections.Generic; using System.Linq;
namespace SecondDimension.Presentation
{
 public sealed partial class M1RuntimeCoordinator : Campaign021.ICampaignPresentationCoordinator021
 {
  Campaign021.CampaignPresentationRegistry021 _campaignRegistry021;
  Campaign021.CampaignPresentationRegistry021 Registry021(){if(_campaignRegistry021==null)_campaignRegistry021=Campaign021.CampaignPresentationRegistry021.LoadFromResources();return _campaignRegistry021;}
  public Campaign021.CampaignPresentationState021 CampaignPresentation021 { get { try{return BuildCampaignPresentation021();}catch(Exception e){return new Campaign021.CampaignPresentationState021{IsAvailable=false,Error=e.Message};} } }
  Campaign021.CampaignPresentationState021 BuildCampaignPresentation021(){var r=Registry021();var active=CampaignPlayable020;var worldId=string.IsNullOrWhiteSpace(active?.WorldId)?"SKYHOME":active.WorldId;var theme=r.Worlds.TryGetValue(worldId,out var t)?t:r.Worlds["SKYHOME"];var chapterId=active?.ActiveChapterId??string.Empty;var ch=!string.IsNullOrWhiteSpace(chapterId)&&r.Chapters.TryGetValue(chapterId,out var cb)?cb:null;var state=new Campaign021.CampaignPresentationState021{IsAvailable=true,ActiveWorldId=worldId,ActiveWorldName=theme.displayName,ActiveChapterId=chapterId,ActiveChapterTitle=ch?.title??string.Empty,BackgroundResource=theme.backgroundResource,FrameResource=theme.frameResource,AmbientAudioCueId=theme.ambientAudioCueId,EnemyPackId=ch?.enemyPackId??string.Empty,BossId=ch?.bossId??string.Empty,LootProfileId=ch?.lootProfileId??string.Empty,WorldThemes=r.Worlds.Count,EnemyProfiles=r.Enemies.Count,BossProfiles=r.Bosses.Count,RecruitProfiles=r.Recruits.Count,LootIcons=r.Loot.Count,MaterialIcons=r.Materials.Count,AudioCues=r.Audio.Count};var worlds=new List<Campaign021.WorldPresentationSummary021>();foreach(var w in r.Worlds.Values.OrderBy(x=>x.displayName)){worlds.Add(new Campaign021.WorldPresentationSummary021{WorldId=w.worldId,DisplayName=w.displayName,ProductionStatus="THEME/FRAME/AUDIO READY",EnemyCount=r.Enemies.Values.Count(x=>x.worldId==w.worldId),RecruitCount=r.Recruits.Values.Count(x=>x.worldId==w.worldId),LootCount=r.Loot.Values.Count(x=>x.worldId==w.worldId),ChapterCount=r.Chapters.Values.Count(x=>x.worldId==w.worldId),MaterialLanguage=w.materialLanguage});}state.Worlds=worlds.AsReadOnly();return state;}
 }
}
