using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using UnityEngine;
using SecondDimension.Gameplay.Creator028;
namespace SecondDimension.Presentation.Creator028
{
 public sealed class CreatorRegistry028 : ICreatorContentCatalog028
 {
  readonly Dictionary<string,CreatorCodeRule028> codes;readonly Dictionary<string,CreatorResourceRule028> resources;readonly Dictionary<string,CreatorInvitationRule028> invitations;readonly Dictionary<string,CreatorWeaponRule028> weapons;readonly Dictionary<string,CreatorContentRule028> content;readonly List<CreatorRoomRule028> rooms;
  public int CodeCount=>codes.Count;public int RoomCount=>rooms.Count;public int InvitationCount=>invitations.Count;public IReadOnlyList<CreatorCodeRule028> AllCodes=>codes.Values.OrderBy(x=>x.CodeId,StringComparer.Ordinal).ToArray();public IReadOnlyList<CreatorRoomRule028> AllRooms=>rooms.AsReadOnly();
  CreatorRegistry028(Dictionary<string,CreatorCodeRule028> c,Dictionary<string,CreatorResourceRule028> r,Dictionary<string,CreatorInvitationRule028> i,Dictionary<string,CreatorWeaponRule028> w,Dictionary<string,CreatorContentRule028> x,List<CreatorRoomRule028> q){codes=c;resources=r;invitations=i;weapons=w;content=x;rooms=q;}
  public static CreatorRegistry028 Load(){var cr=Load<CodeRoot>("SecondDimension/Creator028/Data/CreatorCodeCatalog028");var rr=Load<ResourceRoot>("SecondDimension/Creator028/Data/CreatorResourceCatalog028");var ir=Load<InvitationRoot>("SecondDimension/Creator028/Data/CreatorCharacterInvitations028");var wr=Load<WeaponRoot>("SecondDimension/Creator028/Data/CreatorModifiedWeapons028");var xr=Load<ContentRoot>("SecondDimension/Creator028/Data/CreatorContentUnlocks028");var qr=Load<RoomRoot>("SecondDimension/Creator028/Data/CreatorRoomCatalog028");var reg=new CreatorRegistry028(cr.codes.ToDictionary(x=>x.CodeHash,StringComparer.Ordinal),rr.resources.ToDictionary(x=>x.ResourceId,StringComparer.Ordinal),ir.invitations.ToDictionary(x=>x.InvitationId,StringComparer.Ordinal),wr.weapons.ToDictionary(x=>x.WeaponId,StringComparer.Ordinal),xr.content.ToDictionary(x=>x.ContentId,StringComparer.Ordinal),qr.rooms.ToList());reg.Validate();return reg;}
  public bool TryGetCodeByHash(string h,out CreatorCodeRule028 r)=>codes.TryGetValue(h,out r);public bool TryGetResource(string id,out CreatorResourceRule028 r)=>resources.TryGetValue(id,out r);public bool TryGetInvitation(string id,out CreatorInvitationRule028 r)=>invitations.TryGetValue(id,out r);public bool TryGetWeapon(string id,out CreatorWeaponRule028 r)=>weapons.TryGetValue(id,out r);public bool TryGetContent(string id,out CreatorContentRule028 r)=>content.TryGetValue(id,out r);public bool TryGetRoomForBoard(string def,string board,out CreatorRoomRule028 r){r=rooms.FirstOrDefault(x=>StringComparer.Ordinal.Equals(x.BoardDefinitionId,def)||StringComparer.Ordinal.Equals(x.BoardId,board));return r!=null;}
  void Validate(){if(codes.Count!=300||weapons.Count!=72||invitations.Count!=60||content.Count!=48||rooms.Count!=133)throw new InvalidOperationException("Creator 028 content counts invalid.");if(codes.Values.Any(x=>!x.ExactOncePerCampaign||string.IsNullOrWhiteSpace(x.CodeHash)))throw new InvalidOperationException("Creator code law failed.");if(weapons.Values.Any(x=>!x.ManualEquipOnly||x.ValidSlotIds.Count==0||x.EquipmentTags.Count==0))throw new InvalidOperationException("Creator weapon law failed.");if(rooms.Any(x=>!x.OneVisitPerOperation||!x.CampaignRewardExactOnce||!x.DoesNotAdvanceOperationDay))throw new InvalidOperationException("Creator room law failed.");var roomKeys=new HashSet<string>(codes.Values.Where(x=>StringComparer.OrdinalIgnoreCase.Equals(x.Category,"ROOM_KEY")).Select(x=>x.RewardId),StringComparer.Ordinal);if(roomKeys.Count!=16||rooms.Count(x=>!string.IsNullOrWhiteSpace(x.BonusKeyId))!=16||rooms.Any(x=>!string.IsNullOrWhiteSpace(x.BonusKeyId)&&!roomKeys.Contains(x.BonusKeyId)))throw new InvalidOperationException("Creator room key law failed.");}
  static T Load<T>(string p){var a=Resources.Load<TextAsset>(p);if(a==null)throw new InvalidOperationException("Missing Creator 028 resource "+p);return JsonConvert.DeserializeObject<T>(a.text);}
  [Serializable]sealed class CodeRoot{public CreatorCodeRule028[] codes;}[Serializable]sealed class ResourceRoot{public CreatorResourceRule028[] resources;}[Serializable]sealed class InvitationRoot{public CreatorInvitationRule028[] invitations;}[Serializable]sealed class WeaponRoot{public CreatorWeaponRule028[] weapons;}[Serializable]sealed class ContentRoot{public CreatorContentRule028[] content;}[Serializable]sealed class RoomRoot{public CreatorRoomRule028[] rooms;}
  [Serializable]sealed class CodeDto:CreatorCodeRule028{}[Serializable]sealed class ResourceDto:CreatorResourceRule028{}[Serializable]sealed class InvitationDto:CreatorInvitationRule028{}[Serializable]sealed class WeaponDto:CreatorWeaponRule028{}[Serializable]sealed class ContentDto:CreatorContentRule028{}[Serializable]sealed class RoomDto:CreatorRoomRule028{}
 }
}
