using System;
using System.IO;
using System.Linq;
using Newtonsoft.Json.Linq;
using NUnit.Framework;
using SecondDimension.Gameplay.Creator028;
using SecondDimension.Gameplay.M1;
using SecondDimension.Gameplay.State;
using SecondDimension.Determinism;
using SecondDimension.Presentation.Creator028;
using SecondDimension.Save;
namespace SecondDimension.Tests.EditMode
{
 public sealed class CreatorCodesRooms028Tests
 {
  [Test] public void CatalogHasExactlyThreeHundredCodesAndNoPlaintextCodeField(){var r=CreatorRegistry028.Load();Assert.That(r.CodeCount,Is.EqualTo(300));var a=UnityEngine.Resources.Load<UnityEngine.TextAsset>("SecondDimension/Creator028/Data/CreatorCodeCatalog028");var root=JObject.Parse(a.text);Assert.That(root.ToString().Contains("\"code\":"),Is.False);Assert.That(((JArray)root["codes"]).Select(x=>x["codeHash"].Value<string>()).Distinct().Count(),Is.EqualTo(300));}
  [Test] public void EveryPlayableMapHasOneCreatorRoom(){var r=CreatorRegistry028.Load();Assert.That(r.RoomCount,Is.EqualTo(133));Assert.That(r.AllRooms.Select(x=>x.BoardDefinitionId+"|"+x.BoardId).Distinct().Count(),Is.EqualTo(133));Assert.That(r.AllRooms.All(x=>x.OneVisitPerOperation&&x.CampaignRewardExactOnce&&x.DoesNotAdvanceOperationDay),Is.True);}
  [Test] public void ModifiedWeaponsPreserveFamiliesAndRequireManualEquip(){var r=CreatorRegistry028.Load();var asset=UnityEngine.Resources.Load<UnityEngine.TextAsset>("SecondDimension/Creator028/Data/CreatorModifiedWeapons028");var root=JObject.Parse(asset.text);var w=(JArray)root["weapons"];Assert.That(w.Count,Is.EqualTo(72));Assert.That(w.All(x=>x["manualEquipOnly"].Value<bool>()&&x["artFamilyPreserved"].Value<bool>()),Is.True);Assert.That(w.Select(x=>x["familyId"].Value<string>()).Distinct().Count(),Is.EqualTo(12));}
  [TestCase("five-minute-war","FIVEMINUTEWAR")][TestCase(" 300-30-300 ","30030300")][TestCase("Ab c-12","ABC12")] public void CodeNormalizationIsStable(string raw,string expected){Assert.That(CreatorAccessCommandService028.NormalizeCode(raw),Is.EqualTo(expected));Assert.That(CreatorAccessCommandService028.HashNormalizedCode(raw),Is.Not.Empty);}
  [Test] public void RedeemingTheSameCodeTwiceCannotDuplicateItsCampaignReward(){var service=new CreatorAccessCommandService028();var registry=CreatorRegistry028.Load();var first=service.RedeemCode(CampaignFactory.CreateM0Proof(2028),registry,"FIVE-MINUTE-WAR");Assert.That(first.IsSuccess,Is.True,string.Join("\n",first.Errors));var before=CanonicalJson.Serialize(first.Value);var second=service.RedeemCode(first.Value,registry,"FIVE-MINUTE-WAR");Assert.That(second.IsSuccess,Is.True,string.Join("\n",second.Errors));Assert.That(CanonicalJson.Serialize(second.Value),Is.EqualTo(before));Assert.That(second.Value.Guild.GuildCity.Strategic017H.Campaign019.Playable020.CreatorAccess028.RedeemedCodeIds.Count,Is.EqualTo(1));}
  [Test] public void CodeCategoryCountsAreExactAndCuratedCodeResolves(){var a=UnityEngine.Resources.Load<UnityEngine.TextAsset>("SecondDimension/Creator028/Data/CreatorCodeCatalog028");var codes=(JArray)JObject.Parse(a.text)["codes"];Assert.That(codes.Count(x=>x["category"].Value<string>()=="CHARACTER"),Is.EqualTo(60));Assert.That(codes.Count(x=>x["category"].Value<string>()=="RESOURCE"),Is.EqualTo(80));Assert.That(codes.Count(x=>x["category"].Value<string>()=="WEAPON"),Is.EqualTo(72));Assert.That(codes.Count(x=>x["category"].Value<string>()=="CONTENT"),Is.EqualTo(48));Assert.That(codes.Count(x=>x["category"].Value<string>()=="CHRONICLE"),Is.EqualTo(24));Assert.That(codes.Count(x=>x["category"].Value<string>()=="ROOM_KEY"),Is.EqualTo(16));var r=CreatorRegistry028.Load();Assert.That(r.TryGetCodeByHash(CreatorAccessCommandService028.HashNormalizedCode("FIVE-MINUTE-WAR"),out var rule),Is.True);Assert.That(rule.RewardId,Is.EqualTo("CONTENT028_CREATOR_CHRONICLE_001"));}
  [Test] public void ExactlySixteenRoomsRequireValidCreatorKeys(){var r=CreatorRegistry028.Load();var keys=UnityEngine.Resources.Load<UnityEngine.TextAsset>("SecondDimension/Creator028/Data/CreatorCodeCatalog028");var keyIds=((JArray)JObject.Parse(keys.text)["codes"]).Where(x=>x["category"].Value<string>()=="ROOM_KEY").Select(x=>x["rewardId"].Value<string>()).ToArray();var gated=r.AllRooms.Where(x=>!string.IsNullOrWhiteSpace(x.BonusKeyId)).ToArray();Assert.That(gated.Length,Is.EqualTo(16));Assert.That(gated.All(x=>keyIds.Contains(x.BonusKeyId)),Is.True);}
  [Test] public void SaveAuthorityIsVersionEleven(){Assert.That(SaveEnvelopeV1.CurrentFormatVersion,Is.EqualTo(11));Assert.That(AtomicSaveStore.CurrentSaveFormatVersion,Is.EqualTo(11));}
  [Test] public void V10SaveMigratesToV11WithCreatorDefaults(){var path=Path.Combine(Path.GetTempPath(),"second_dimension_creator028_"+Guid.NewGuid().ToString("N")+".json");try{var campaign=CampaignFactory.CreateM0Proof(1028);var raw=JObject.Parse(CanonicalJson.Serialize(campaign));var playable=raw["Guild"]?["GuildCity"]?["Strategic017H"]?["Campaign019"]?["Playable020"] as JObject;Assert.That(playable,Is.Not.Null);playable.Remove("CreatorAccess028");var envelope=new JObject{{"SaveFormatVersion",10},{"ContentAuthorityVersion",campaign.ContentAuthorityVersion},{"CampaignGuid",campaign.CampaignGuid},{"CampaignSeed",campaign.CampaignSeed},{"DisplayTimestampUtc","1970-01-01T00:00:00.0000000Z"},{"CampaignState",raw},{"CanonicalStateHash",CanonicalJson.Sha256Hex(raw)},{"MigrationHistory",new JArray("save_v1_to_v2_m1_state_defaults","save_v2_to_v3_m2_battle_defaults","save_v3_to_v4_m2_art_growth_defaults","save_v4_to_v5_progression_foundation_defaults","save_v5_to_v6_guild_city_foundation_defaults","save_v6_to_v7_campaign_runtime_019_defaults","save_v7_to_v8_campaign_playable_020_defaults","save_v8_to_v9_progression_abyss_covenant_022_defaults","save_v9_to_v10_world_gate_expedition_runtime_023_defaults")}};File.WriteAllText(path,CanonicalJson.Serialize(envelope));var loaded=new AtomicSaveStore().ReadWithRecovery(path);Assert.That(loaded.IsSuccess,Is.True,string.Join("\n",loaded.Errors));Assert.That(loaded.Value.SaveFormatVersion,Is.EqualTo(11));Assert.That(loaded.Value.MigrationHistory,Contains.Item("save_v10_to_v11_creator_codes_rooms_028_defaults"));var state=loaded.Value.CampaignState.Guild.GuildCity.Strategic017H.Campaign019.Playable020.CreatorAccess028;Assert.That(state,Is.Not.Null);Assert.That(state.RedeemedCodeIds,Is.Empty);Assert.That(loaded.Value.CampaignState.Guild.Recruits.Count,Is.EqualTo(campaign.Guild.Recruits.Count));}finally{if(File.Exists(path))File.Delete(path);if(File.Exists(path+".bak"))File.Delete(path+".bak");if(File.Exists(path+".tmp"))File.Delete(path+".tmp");}}
 }
}
